### ISSUE TITLE
[2021 fall] ICML 2021 Learning Transferable Visual Models From Natural Language Supervision (20213513)

### ISSUE THREAD

**Issue by atjeong** [awesome-davian/awesome-reviews-kaist#104]

**Comment by GuilJung** [comment]
안녕하세요, 리뷰를 읽다가 추가됐으면 하는 부분들에 대해서 코멘트 남깁니다.

1. 제로샷 전송, 제로샷 점수 라는 것이 무엇인지 설명이 있으면 좋을 것 같습니다.
2. '해당ㅇ 데이터, ㅊ처음,' 오타 있습니다
3. 앙상블 기법에 대한 자세한 설명은 없는건가요??
4. Figure 12 13에 대해 설명해주는 내용이 더 있었으면 좋겠습니다. 쉽게 알수있다고 나와있는데 익숙치 않은 사람들은 왜 이 테스트가 그런 결과로 도출되는 것인지 잘 이해되지 않을 것 같습니다.

재미있게 잘 읽었습니다:)

**Comment by bangjh0430** [comment]
안녕하세요. 전기및전자공학부 석사과정 방제현입니다.

리뷰에 대해서 몇가지 코멘트 남깁니다.

1. 영단어가 익숙한 용어들은 굳이 한국어로 번역하지 않고 쓰시는 게 자연스러울 것 같습니다.
2. "~다." 와 "~입니다"가 동시에 사용되고 있는데 하나로 통일하는 것이 좋을 것 같습니다.
3. Problem definition에 작성된 내용이 problem definition이 아니라 abstract입니다. 논문에서 해결하고자 하는 문제에 대한 설명을 중심으로 작성하시면 좋을 것 같습니다.

이상입니다.

리뷰 잘 읽었습니다!

**Comment by anneshj** [comment]
안녕하세요, 최현진입니다.

- Figure1 그림 크기를 키우면 좋을 것 같습니다.
- Firgure1에 나오는 CLIP의 전체 프로세스: (1) Contrastive pre-training, (2) Create dataset classifier from label text, (3) Use for zero-shot prediction 각 단계에 대한 설명(작업이 어떻게 이어지는지)이 있으면 좋겠습니다.
- Zero-shot scheme이 어떤 것인지에 대한 설명이 있으면 좋겠습니다.
- Prompt Engineering and Ensembling Section에서 Prompt Engineering과 Ensembling의 효과에 대한 이야기 이전에 이것이 무엇인지에 대한 설명이 추가되면 좋겠습니다.

리뷰 잘 읽었습니다.
