### ISSUE TITLE
[2021 fall] CVPRW 2021 Shot in the Dark - Few-Shot Learning with No Base-Class Labels (20213093)

### ISSUE THREAD

**Issue by atjeong** [awesome-davian/awesome-reviews-kaist#106]

**Comment by Seung-HO-HAN** [comment]
안녕하세요, 김경수 교수님 연구실 박사과정 한승호(20215618)입니다.
업로드해주신 awesome review 잘 읽어보았습니다.

Topic 관련 키워드들에 대해 쉽고 상세한 설명을 해주신 덕분에, 큰 문제없이 읽을 수 있었습니다. 감사합니다.
몇가지 수정사항만 반영하시면 될 것 같습니다.

**[Peer review]**
1. Figure의 caption이 아래에 위치하면 좋을 것 같습니다.
2. FSL을 Image Classification 이외에 **다른 field에 적용한 사례**가 있는지 궁금합니다.
3. SSL이 **부정확한 label을 생성하는 경우**에 대처함으로써, FSL의 성능을 더욱 향상시킬 수 있을 것 같습니다. 이와 관련된 연구가 있는지 궁금합니다.

감사합니다.
한승호 드림

**Comment by bulsajyo** [comment]
안녕하세요 기계공학과 박사과정 오상윤(20215201) 입니다.
먼저, 논문을 이해하기 쉽고 보기 좋게 정리해주셔서 리뷰 잘 읽어보았습니다.
아래에 코멘트 남겨드립니다.

 1. 이미지 캡션이 작고 밝은 회색이라 눈에 잘 안띄어서 눈에 잘 띄도록 하면 좋을 것 같습니다.

  2. Figure12의 이미지들이 작게 나와서 나눠서 업로드하면 좋을 것 같습니다.
  3. 결과 experiment1에서 mini ImageNet과 tiered ImageNet에서는 전체적으로 좋은 정확도를 보였는데, mini&CUB에서는 전체적으로 많이 낮은 정확도를 보여서 세 경우가 어떤 차이가 있는 건지, 정확도 하락의 원인이 무엇인지 궁금합니다.

**Comment by yujin05** [comment]
안녕하세요 전기 및 전자공학과 석사과정 이유진(20213472) 입니다.
올려주신 논문 리뷰 인상 깊게 읽었습니다. 명확하게 설명해주셔서 자세하게 알지 못했던 부분에 대해서 잘 알 수 있는 기회가 되었습니다.
몇 가지 코멘트만 남겨드립니다.

[코멘트]
수식이 정확하게 되어있지 않아서 보는데 불편함이 있어서 이 부분을 수정해주시면 좋을 것 같습니다. 

Figure와 본문 사이에 띄움이 있다면 보기 더 편할 것 같습니다

Figure 12 에서 x축이 base class, y축이 novel class에 대한 accuracy라는 것을 명시해주시면 figure를 해석하기 더 좋을 것 같습니다.

**Comment by bo-10000** [comment]
@Seung-HO-HAN 
1. Figure caption이 제 브라우저에서는 아래에 위치한 것으로 나오는데, 혹시 다르게 보이신다면 스크린샷 첨부해주시면 감사하겠습니다
2. 본문에서 classification 이외의 다른 task에서도 FSL이 사용된다고 간단히 언급하였는데, 혹시 관련 연구가 더 궁금하시다면 다음 링크 참고하시면 좋을 것 같습니다! 본문에서는 내용이 너무 길어질 것 같아서 추가로 언급하지 않았습니다. ([semantic segmentation](https://hydragon-cv.info/entry/Few-Shot-Image-Semantic-Segmentation), [object detection](https://blog.si-analytics.ai/7?category=894440)) 
3. 본 논문에서는 해당하는 경우에 대한 보완책은 따로 제시하지 않고 있습니다. 본 논문의 한계점으로 지적받은 부분이기도 하지만, 현존하는 SOTA SSL 기법들을 (거의 그대로) 가져와 FSL에 적용한 것이기 때문에 새로운 기술은 거의 추가되지 않았다고 보아도 무방합니다. 

@bulsajyo 
3. 위의 Experimental setup 문단에서 간단히 언급하기는 했는데, miniImagNet&CUB 데이터셋은 miniImageNet과 CUB 두 가지의 데이터셋을 섞어서 구성한 것으로, cross-domain에 대한 robustness를 확인하기 위한 것입니다. 때문에 도메인이 같은 것들로 구성된 miniImageNet과 tiered ImageNet에 비해서 전반적으로 성능이 떨어진 것을 확인할 수 있습니다. (그러나 Combined가 가장 성능이 높고, UBC-FSL과 FSL baseline의 성능이 크게 차이나지 않는다는 전체적인 경향은 비슷합니다.)

이외의 서식 관련 이슈들은 모두 수정하였습니다! 코멘트 모두 감사드립니다.
