### ISSUE TITLE
[2021 fall] CVPR 2021 Learning Continuous Image Representation with Local Implicit Image Function (20214384)

### ISSUE THREAD

**Issue by atjeong** [awesome-davian/awesome-reviews-kaist#107]

**Comment by fxnnxc** [comment]
You can find the article here
https://awesome-davian.gitbook.io/awesome-reviews/paper-review/2021-fall-paper-review/cvpr-2021-liif-eng

**Comment by YoonjinXD** [comment]
1. 섹션 2의 'Latent code for continuous position' 부분의 'Latent Code의 개수는 이미지의 사이즈의 사이즈 만큼 있으며' 라는 문장의 의미를 이해하기 조금 어려운 것 같습니다. '사이즈의 사이즈만큼' 에 대한 부가 설명이 필요하지 않을까 생각합니다
2. 섹션 2의 'Continuous Representation using Latent Code' 부분에서 제시된 continuous representation 수식의 S_t/S <- 이 값이 어떤 걸 의미하는 지 궁금합니다. 수식 설명을 짧게 추가해주시면 좋을 것 같아요.
3. 섹션 4의 'Local Ensemble' 부분에서 제시한 Figure들에 대해 좀 더 자세한 설명을 해주면 좋겠습니다. (e.g. Figure에 제시된 z 값들이 어떻게 선택되는지)
4. EDSR 인코더와 RDN 인코더의 차이에 대해 짧게 짚어주실 수 있나요?

**Comment by fxnnxc** [comment]
1. 사이즈의 사이즈라는 부자연스러운 맥락을 수정하여, Latent 이미지 픽셀 수 HW 만큼 latent code가 있으며, latent code인 이유는 HW가 Low Resolution이기 때문이다라는 방식으로 설명을 바꿨습니다.

2.  S_t 는 Z_t 와 x로 생기는 사각형의 넓이라는 설명을 추가하였습니다. 

3. x에 대해서 어떤 latent code가 선택되는지, 그 기준(거리)는 무엇인지 설명하였습니다. 

4. EDSR과 RDN 둘 다, 이미지 인코더로 간단한 설명과 차이점을 기술하였습니다. 

Pull Request를 올려 업데이트 되는대로 변경된 포스트 확인하실 수 있습니다. 
**꼼꼼한 리뷰 감사합니다** 😃👍

**Comment by gyuhyeonsim** [comment]
안녕하세요 해당 논문 관련한 도메인 지식이 없었는데, 친절한 설명덕분에 재밌게 읽었습니다 :)
몇가지 질문이 있어서 아래 적어둡니다!

1. Latent Code for continuous position 섹션에서, 4.3 hyperref가 잘못걸려있는것 같습니다.
2. Latent Code for continuous position 섹션에서 z*가 가까운 4개의 latent code로 정해진다고 하셨는데 의미를 구체적으로 알고싶습니다! 단순히 linear interpolation 하는것인가요?
3. Local ensemble이라는 방법은 이 논문에서 제안된 방법인가요?!
3. [0,H]×[0,W] 이미지의 의미가 HxW resolution의 이미지라는 것과 다른것인가요?

**Comment by fxnnxc** [comment]
친절한 리뷰 감사합니다. 프로젝트 진행하느라 답변이 조금 늦었습니다 .ㅜㅜ 

언급해주신 하이퍼링크 수정하였습니다!  👍  

질문대답 
1. Linear Interpolation: 넵 맞습니다.  가까운 4개를 고르고 각각 픽셀값(RGB)을 생성해냅니다. 그리고 4개에서 거리만큼 interpolation이 된다고 생각하시면 됩니다. (실제로는 면적으로 계산)
2. local ensemble은 앙상블 방법이라서 다른 분야에서도 많이 사용되는데, continuous representation을 나타내기 위해서는 여기서 먼저 사용한 것으로 확인됩니다. 
3.  HxW이미지를 사용하는데,  학습할 때, image의 사이즈를 생각하면 X의 범위가 [0,H]×[0,W] 이지만 실제로는 [0,1]x[0,1]로 변경해서 사용합니다. X의 범위를 나타내기 위해서 표현한 방식입니다. 

추가적인 질문있으시면 답해드리겠습니다. 감사합니다 :)
