### ISSUE TITLE
[2021 fall] ICCV 2019 Toward Real-World Single Image Super-Resolution - A New Benchmark and A New Model (20203515)

### ISSUE THREAD

**Issue by atjeong** [awesome-davian/awesome-reviews-kaist#108]

**Comment by juyebshin** [comment]
안녕하세요, 신주엽입니다.
먼저 리뷰 잘 읽었습니다. SISR task에 대해 전반적으로 이해할 수 있었습니다.

리뷰를 읽으면서 제가 정리한 것 아래에 작성하였습니다

- bicubic degradation, multiple degradation 등의 용어에 대해서 간략한 추가 설명이 있으면 이해하기 더 수월할 것 같습니다
- 전체적으로 수식을 잘 나오도록 수정하면 좋을 것 같습니다 ($을 $$로 수정, $$ 열고 닫고 잘 되었는지 확인 등)
- 중간중간 오타 수정 확인 필요할 것 같습니다
- Related work에서 KPN을 개선한 것이 본 논문에서 제시하는 LP-KPN이라 생각하는데, 이 모델의 한계점이 무엇인지, 또 KPN이 어떤 방식으로 기술적으로 설명해주시면 좋을 것 같습니다
- Experiment의 데이터셋 관련해서 각 모델들을 BD, MD, RealSR에서 각각 학습을 한 후 테스트를 진행한 것이 맞는지 궁금합니다 (당연히 그럴 것이라 생각하는데 표현을 해주면 좋을 것 같습니다)

감사합니다

**Comment by JunbongJang** [comment]
안녕하세요, 장준봉입니다.
리뷰 잘 읽었습니다. 

- Related work 에서 kernel prediction network 의 좋은점은 말하셨는데 어떻게 작동하는지도 설명해주세요
- Laplacian pyramid 에서 쓰이는 laplacian decompostion 과 laplacian reconstruction 에 대해서 설명해주세요
- 왜 Laplacian pyramid 를 썼는지 설명해주세요
- Experimental setup 에서 네트워크 structure 에 대해서 더 설명해주세요. 예를들어 per-pixel convolution 은 무엇이고 shuffle 은 무엇인지.
- 궁금한점은 LP-KPN 가 k=5 일때 가장 잘된다고 하셨는데 kernel size 를 늘리면 왜 performance 가 낮아지는지 궁금합니다. 
- typo : "빠른 convergence 가져다 주며 denoising 부문에앙서" --> 부분에서 
- conclusion 에서 글이 중간에 끊긴거 같.

감사합니다

**Comment by mjbooo** [comment]
안녕하세요 AI대학원 석사과정 이민재(20214501) 입니다.

> problem definition부분을 잘와닿게 잘쓰신 것 같아서 해결해야하는 문제가 무엇이닞 쉽게 파악할 수 있었습니다. 
> domain specific할 수 있는 용어(blur kernel, spatially variant, bicubic downsampling, ...)에 대해서 간단한 설명이 있으면 훨씬 읽기 수월할 듯 합니다. 
> baseline model이었던 BD, MD ... 에 대한 간단한 설명과, 논문에서 다루는 모델과의 차이점을 같이 병기하면 훨씬 눈에 잘 들어올 것 같아요
> image pair registration 에서 왜 post processing이 필요하다고 하셨는지 유추가 잘 안됩니다... ㅜ
> KPN과 LP-KPN 파트의 핵심 차이는 Laplacian Pyramid 부분일텐데 이 부분이 어떠 ㄴ원리로 더 고해상도를 얻을 수 있는지 큰 흐름이 잘 파악되지 않습니다. 
> 인라인 수식 삽입 문제는 윗분들이 말씀해주신 것 같아 생략하겠습니다. 
> LP part가 main contribution일 것이라고 예상하는데, 이 부분을 conclusion에 넣으면 좋을 것 같습니다.

 

정성들인 논문 리뷰 감사합니다!
