### ISSUE TITLE
[2021 fall] CVPR 2021 pixelNeRF: Neural Radiance Fields from One or Few Images (20204234)

### ISSUE THREAD

**Issue by atjeong** [awesome-davian/awesome-reviews-kaist#109]

**Comment by juyebshin** [comment]
안녕하세요, 신주엽입니다.
먼저 리뷰 잘 읽었습니다.
View synthesis task에 대해 전반적으로 이해할 수 있는 좋은 글이였습니다.

리뷰를 읽으면서 추가하거나 수정하면 좋은 점 아래 정리해보았습니다.

- 문장에서 수식이 잘 나오도록 수정이 필요할 것 같습니다 ($를 $$로 수정)
- 제가 이해가 부족한 것일 수 있지만, 섹션 3.1에서 $x,d$가 네트워크를 통해 구하고자 하는 prediction이 맞는지 알고 싶습니다. $d$가 무엇을 의미하는지, NeRF와 다르게 feature map을 이용하면서 어떤 장점이 있는지 간략하게 예시와 함께 설명해주면 좋을 것 같습니다
- Conclusion에서 process of learning scene prior가 method에서 언급이 되었는지 확인하면 좋을 것 같습니다

감사합니다

**Comment by JunbongJang** [comment]
안녕하세요 장준봉입니다.
리뷰 잘 읽었습니다. 제가 오늘 세개 본 리뷰 중에서 가장 길지만 잘 쓴 리뷰였습니다.
덕분에 Nerf 에 대해서도 배울 수 있었네요. pixelNerf 라는게 nerf에 spatial feature 정보만 추가한 것이군요.

comments 를 몇개 해드리자면
- 저는 NeRF 논문을 먼저 읽고 NeRF 를 제대로 이해하니 pixelNeRF 리뷰가 더 이해가 되더군요. NeRF 가 뭔지도 모르는 독자들을 위해서 Related Work section 에서 NeRF 설명부분을 좀 더 추가해도 좋을 것 같습니다. 예를들어 density σ 가 무엇을 의미하는지, Volume rendering 이 무엇인지 설명해주세요.
- Related work section 에서 Link below :) 밑에 링크가 안보입니다.
- Related work section 에서 learned prior 가 뭔지 더 설명해주세요. Data 에서 추가적으로 가져오는 정보인가요?
- Experiments section 에서 PSNR 과 SSIM 공식에 들어가는 문자들이 각각 무엇을 의미하는지 설명해주시면 좋겠습니다.

**Comment by ksalsw1996DM** [comment]
안녕하세요 이승우 입니다.
리뷰를 하면서 NeRF에서부터 시작하여 그 한계점, 어떻게 spatial feature 정보를 추가하여 더 적은 image를 활용하여 3d object를 만들어내었는지 배울수 있었던 좋은 기회였습니다.

제 comment는

- DTU MVS dataset의 실험 결과에 대해서 간단한 추가 설명을 해주실수 있을까요? novel view에 대비 random한 이미지라고 생각이 되어서요.
- Single shot PixelNeRF에 대해서 설명해주시는 부분에서, 'NeRF에서와 동일한 방법으로 volume rendering을 진행합니다.' 이부분에 대한 설명이 추가된다면 좋을것 같습니다.
- 평가때 사용되는 metric뿐만 아니라, 학습에 사용되는 loss에 대한 설명이 추가가 된다면 좋을것 같습니다.

감사합니다
