### ISSUE TITLE
[2021 fall] CVPR 2021 GFP-GAN - Towards Real-World Blind Face Restoration with Generative Facial Prior (20204328)

### ISSUE THREAD

**Issue by atjeong** [awesome-davian/awesome-reviews-kaist#110]

**Comment by oglee815** [comment]
20213784/이현제

- Introduction에서 해당 페이퍼에서 다루는 문제와 모티베이션이 설명이 잘 되어있습니다.
- 전체적인 흐름 파악이 쉽도록 잘 설명이 되어 있습니다.
- 수식은 나와있으나 수식에 대한 자세한 설명이 없어서, 이에 대해 보충 설명이 있으면 좋을 것 같습니다.
- 리뷰만 읽고 이해하기에는 설명이 부족한 것 같습니다.

Error
- Related Work에 내용이 없습니다.
- 섹션 3에서 수식들이 깨져있습니다.

**Comment by oglee815** [comment]
20213784 / 이현제

좋은 리뷰 잘 봤습니다.
Introduction과 Motivation이 잘 정리되어 있어서 읽기 좋았습니다.

다만,

- Related Works이 비어있고, Result에 별다른 해석이 없어서 아쉬웠습니다.
- 섹션 3에서 수식이 깨져있습니다.
- U-Net structure 에 관한 간략한 설명이 있으면 좋을 것 같습니다.

감사합니다.

**Comment by SeunghoonYang** [comment]
안녕하세요,
카이스트 기계공학과 석사과정 20213361 양승훈입니다.

- Related Works의 링크가 제대로 걸려있지 않은 것 같습니다.
- 윗 분께서 섹션 3의 수식이 깨져있다고 언급해주셨는데, 4에서도 그래보이니 전체적으로 수식 점검이 필요해보입니다.
- 섹션 3이 메인 내용인데, 이 부분을 읽으면서도 GPF-GAN이 정확히 어떤 프로세스를 거치는지 제대로 파악하지 못했습니다. 본문의 내용이 Figure의 흐름에 맞게끔 수정되면 좋을 것 같습니다.

**Comment by hsl323** [comment]
안녕하세요,
naver 이현수 입니다.
- problem definition이 잘 정리되어 좋은 것 같습니다.
- 현재 비어있는 Related Works에서 간단하게라도 설명해주시는 것이 뒷내용을 이해하기 좋을 것 같습니다.
- 윗분들 말씀대로 수식이 정리되면 좋을 것 같습니다.
- 섹션 3 시작부분에 `facial component loss 와 identity preserving loss 가 제안 되었습니다.` 라고 되어있는데 설명은 따로 되어 있지 않아 논문도 기존에 존재하던 loss를 그대로 사용한 것인지 새롭게 제안했다는 것인지 잘 모르겠습니다. 그 부분이 설명이 되어 있었으면 좋겠습니다. (논문의 contribution중 하나인지 아닌지를 잘 모르겠습니다.)
