### ISSUE TITLE
[2021 fall] CVPR 2020 ScrabbleGAN; Semi-Supervised Varying Length Handwritten Text Generation (20214276)

### ISSUE THREAD

**Issue by atjeong** [awesome-davian/awesome-reviews-kaist#111]

**Comment by daheekwon** [comment]
ScrabbleGAN

논문 요약 감사드립니다 :) 아래는 제가 생각한 수정사항입니다.
1. prob-definition부분에서 cnn을 사용해도 over receptive field를 사용하면 rnn의 sequential한 특징을 (적어도 local하게는) 충분히 활용할 수 있음 언급해주면 좋을 것 같습니다. 

2. method의 모델 구조 단락에서 not trivial -> non trivial로 바꿔야할 것 같습니다. 

3. method의 loss func 밑에 다음로 -> 다음으로 typo가 있습니다. 

4. method의 loss func부분에 lambda에 대한 설명도 한문장 추가해주면 좋을 것 같습니다. 

5. Experimental setup에서 evaluation metric 수식을 써주시면 좀 더 직관적으로 이해 가능할 것 같습니다. 

감사합니다.

**Comment by IamHanJungMin** [comment]
좋은 논문 리뷰 잘 읽었습니다. 감사합니다.
아래 코멘트를 남겨 드리오니 업데이트에 참고 부탁 드립니다.

- 이 분야가 생소한 독자들을 위해 Handwritten Text Recognition(HTR) 모델에 대한 목적이나 활용 분야에 대한 추가적인 설명이 간단하게라도 있으면 좋을 것 같습니다.
- 저자가 제시하는 아이디어 및 모델의 구조에 대해 보다 많은 정보가 포함된 이미지를 추가하면 이해하는데 더 도움이 될 것 같습니다.
- 독자들의 원리에 대한 이해를 돕기 위해 Reference & Additional materials 부분에 본 논문에 대한 발표 동영상을 링크해도 좋을 것 같습니다. 링크는 아래를 참조 부탁 드립니다.
https://www.youtube.com/watch?v=jGG5Q8S1Rus

**Comment by jungyubaik** [comment]
RNN으로 부터 탈피하여 CNN으로 나아가고자 하는 방향의 논문 리뷰 인상 깊었습니다.
다만 한 가지 제안 사항이 있어 남겨드립니다.

본 논문은 α값에 따라 학습의 정도가 달라지는 것을 보입니다. α에 대한 정의와 이에 따라 달라지는 학습에 설명이 추가되었으면 좋겠습니다. 감사합니다:)

**Comment by rlgnswk** [comment]
안녕하세요 해당 리뷰 작성자인 김기훈입니다.

건설적인 피드백 감사드립니다.

주신 피드백들을 반영하여 글을 업데이트 하였습니다!
시간이 괜찮으시다면 한번 봐주시고 평가해주시면 감사하겠습니다!

감사합니다.
김기훈 드림.
