### ISSUE TITLE
[2021 fall] CVPR 2020 Squeeze-and-Attention Networks for Semantic segmentation (20213564)

### ISSUE THREAD

**Issue by atjeong** [awesome-davian/awesome-reviews-kaist#112]

**Comment by pmh9960** [comment]
사진이 하나도 보이지 않음.

**Comment by amy-hyunji** [comment]
1. Idea에서 `기존 제한점을 극복하였고` 부분에서 기존의 제한점이 무엇인지 명시해주면 좋을 것 같습니다.
2. Result에서 numbering이 잘못되어 있는 것 같습니다.
3. 위에 언급된 바와 같이 사진이 안 보입니다!

**Comment by pmh9960** [comment]
안녕하세요 사진을 고쳐주셔서 감사합니다. 덕분에 편하게 읽었습니다.
몇 가지 여쭤보고 싶은 부분이 있어서 적어보겠습니다. 이에 대한 보충을 논문 리뷰에 반영해주시면 감사드리겠습니다.

1. 논문 초반부에 pixel-grouping에 대한 설명이 있고 이를 보완하겠다고 했는데 이에 대한 셜명이 뒤 method 부분에서 조금 부족한 것 같습니다. 제 생각에는 spatial attention을 줄 것이고 이 attention map이 group 별로 smooth하기 때문에 단순 conv만으로 이루어진 것 보다 좋아졌다고 생각하는데 저자들도 이러한 얘기를 했는지 궁금합니다.
2. SENet 외에도 residual connection에 attention module을 넣는 모델은 이 외에도 2020년 이전에 굉장히 많은 것으로 알고 있습니다. 그중에는 spatial attention을 적용한 dual attention, cbam ... 등으로 제가 기억하고 있습니다. 혹시 어려우시겠지만 이 논문에서 그런 실험에 대한 부분이 부족한 것 같은데 실험하지 않은 이유나 비교에 대한 설명이 있는지 궁금합니다.

리뷰 잘 읽었습니다~

**Comment by khslily98** [comment]
안녕하세요.
작성해주신 글 잘 읽었습니다.  잘 정리된 리뷰 덕분에 Semantic segmentation에 관한 새로운 네트워크를 알게 되었습니다. 아래는 몇 가지 보완하시면 좋을 것 같은 점 들입니다.

1. 저도 사진이 잘 보입니다! 수정해주셔서 감사합니다 :)
2. Problem Definition과 Modivation부분에 내용을 조금 더 추가해주셨으면 합니다. 예를 들어 Problem Definition부분에서는 RGB 이미지에서 각 픽셀을 특정 라벨로 분류하는 작업이 왜 필요한 작업인지, 어떤 부분이 힘든지를 알려주셨으면 합니다. 그리고 Related work 부분에서는 예를 들어 Multi-scale context를 설명하신 부분에서 "Laplacian pyramid structure에서 multi scale feature를 결합하는 방식과 multi-path RefineNet에서 multi-scale input에서 feature를 추출해 결합하는 방식을 사용" 이라고 하셨는데, Laplacian pyramid structure, multi scale feature, multi-path RefineNet 등을 설명해주시면 감사하겠습니다.
3. 저자는 semantic segmentation이 두개의 독립된 차원(pixel-wise prediction and pixel grouping)으로 이루어졌다는 새로운 생각으로 부터 이러한 네트워크를 설계했다고 언급해주셨는데, 각각을 독립된 차원으로 고려하여 네트워크를 설계한 것이 성능 향상에 왜 도움이 되었는지가 궁금합니다. 즉 pixel-wise는 각 픽셀이 무슨 물체인지 판단하는 것이고, pixel grouping은 픽셀간의 유사도를 통해 연결성을 강조하는 것 이라고 하셨는데, 제 생각으론 각각을 함께 생각하는 것이 더 도움이 될 것 같은데 왜 독립된 차원으로 하였을 때 더 우수한 성능을 보인 것인지 궁금합니다.

감사합니다, 남은 학기 함께 화이팅해요!😊
