### ISSUE TITLE
[2021 fall] CVPR 2021 Dynamic Head - Unifying Object Detection Heads with Attentions (20213523)

### ISSUE THREAD

**Issue by atjeong** [awesome-davian/awesome-reviews-kaist#113]

**Comment by HATAEWOOK** [comment]
문화기술대학원 석사과정 하태욱(20214631)입니다. 
섹션별로 리뷰 작성하였습니다 

## 2. Related Work
### Scale-awareness
- 본문의 "다른 level에서 추출되는 feature간에는 눈에 띄는 semantic gap이 존재하게 되는데"의 semantic gap이 어떤 건지 설명이 필요하다고 생각합니다
- semantic gap의 감소가 어떻게 detector를 scale-awareness하게 하는지 설명이 필요할 것 같습니다
### Task awareness
- Task에 대한 참고 이미지가 있으면 좋을 것 같습니다(_bounding box를 치는 방법, 객체의 중심점을 잡는 방법, 객체의 특징점들을 찾아 그 점들을 이어 객체를 감지하는 방법_이 어떤 것인지)
## 3. Our Approach
### Dynamic Head: Unifying with Attentions
- 아마 공식으로 생각되는 부분들이 누락되어있습니다
## 4. Experiment & Result
### Ablation Study
- "3개의 attention function 중 spatial attention function에 해당하는 차원이 지배적" 이라는게 무슨 의미인지 잘 모르겠습니다.

**Comment by yoonjii** [comment]
Scale ration

**Comment by yoonjii** [comment]
친절한 설명 감사드립니다.

- Typos
4. Experiment & Result (scale ration > scale ratio)
- Opinions or questions about the article
전체적으로 notation과 평가 지표에 대해 좀 더 자세한 설명이 필요할 듯 합니다.

**Comment by hannabros** [comment]
안녕하세요, 선한결이라고 합니다.
논문 리뷰 재밌게 잘 보았고 아래 제 리뷰 드리오니 참고바랍니다.

2. Related Work
- 좋은 object detection head에 대한 조건 3가지 중심으로 잘 서술했습니다.
- 각 항목에 대한 주요 관련 논문도 참고로 표시하면 좋을 것 같습니다.

3. Our Approaches
- Simple dynamic head structures의 이미지가 중복됩니다. 하나의 이미지로 표현해도 될 것 같습니다.
- Dynamic Head와 관련된 이미지가 거의 대부분 유실되어 구체적인 내용을 파악하기 어렵습니다. ‘파이’와 관련된 수식과 관련된 내용은 한글이 아닌 수식에서 쓰인 알파벳으로 표기하면 더 이해하기 쉬울 것 같습니다.
- Two-stage detector에 dynamic head를 적용할 때 scale-awareness, spatial-awareness attention을 거친 뒤에 roi pooling을 적용하고 task-aware attention을 거치게 됩니다. -> roi를 ROI

4. Experiment & Result
- 4번 항목은 최종 결과만 써져있습니다. 어떤 실험 데이터를 바탕으로 테스트를 했는지 명시가 필요해 보입니다. 또한 어떻게 실험했는지에 대한 내용에 명시가 필요해 보입니다.
- Ablation Study에서 가로축(AP, AP_50, AP_75, AP_S, AP_M, AP_L)에 대한 셜명이 있으면 좋을 것 같습니다.
- Scale ration는 학습된 고해상도 가중치를 저해상도 가중치로 나눈 값을 의미하며 해당 ratio에 대한 그래프는 왼쪽과 같습니다. -> scale ration 오타, 그래프가 왼쪽에 있지 않습니다.
- Head의 depth의 성능에 따른 표에서 baseline이 무엇인지 명시가 필요해보입니다. 또한 여기서 계산량이라는 것은 계산 시간을 의미하는 것인가요?
- Generalization on Existing Object Detector에서 보면 1.2~3.2AP 정도 향상이 되었다고 하는데 가로축 Method도 AP, AP_50, AP_75로 되어있습니다. 이 AP 간의 차이가 있나요? 수치 표현에 대해 잘 모르겠지만 가로축과 세로축 모두 AP로 표기하는지 궁금해 여쭤봅니다.

**Overall**
- 이상적인 object detection head에 대한 3가지 조건과 이에 따른 각각의 approach를 잘 써주셨습니다. 다만 approach에서 보충 설명에 필요한 이미지와 수식이 보이지 않아 이 부분은 수정이 필요해보입니다.
- 실험 부분은 결과만 써져있고 실험 데이터, 방식에 대한 추가 설명이 필요해보입니다.
- 실험 결과가 여러개 있는데 그것들을 중분류로 나눠서 표시하면 더 잘 보일 것 같습니다.
- 이건 제 사담이긴 하지만 오늘의 교훈을 논문과 관련된 내용으로 작성하면 더 좋을 것 같습니다.
