### ISSUE TITLE
[2021 fall] MICCAI 2021 Quality-Aware Memory Network for Interactive Volumetric Image Segmentation (20208204)

### ISSUE THREAD

**Issue by atjeong** [awesome-davian/awesome-reviews-kaist#114]

**Comment by earlgrey97** [comment]
안녕하세요. 전자과 대학원 석사과정에 재학중인 박나현입니다.
전체적으로 깔끔하게 잘 적어주셔서, 재밌게 읽었습니다.

몇가지 사소한 부분만 comment 남깁니다..!
1) Figure1 사진이 뜨지 않는데, 확인 부탁 드립니다.
2) Motivation에 'reviwer'이라고 적어주셨는데, reviewer인 것 같은데 오타가 난 것 같습니다. 
3) Idea 부분에서도 같은 오타를 내신 것 같은데, reviewer가 원래 의도하신 게 맞다면 수정하시면 좋을 것 같습니다. 나머지 섹션들에서도 똑같이 표기하신 게 몇 개 있는 것 같은데, 확인해보시면 좋을 것 같습니다.
4) Figure 5까지는 따로 표기를 하신 것 같은데, figure 4,5,6은 따로 표기가 뜨지 않아, 본문에서 각 figure를 언급하실 때 읽는 사람 입장에서는 헷갈릴 수 있을 것 같습니다. 특히, figure 6의 그림에는 figure1이라고 적혀있어서 더더욱이요... 이 부분을 확실히 표시해주시면 좋을 것 같습니다.
5) interactive segmentation engine 섹션의 propagation 파트에서 query image I_{k}의 수식이 깨진 것 같습니다.

감사합니다.

**Comment by johnlee92** [comment]
안녕하세요. NAVER 재직중인 이재현입니다.
리뷰를 잘 작성해주셔서 재밌게 읽었습니다. 몇 가지 코멘트 남깁니다.

1. 리뷰어의 의견이 중간중간 삽입되어 있어서 더 풍부한 리뷰가 된 것 같습니다.
2. 경어체와 평어체가 혼용되어 있는데, 통일되면 자연스럽게 읽힐 것 같습니다.
3. 2D와 3D를 사용하는 두 방법을 적절히 혼합하여 저자가 원하는 tradeoff 지점을 찾은 것 같습니다.
4. Dice Similarity Coefficient 평가 척도를 알게 되어 좋았습니다.

감사합니다.

**Comment by dkmv0623** [comment]
안녕하세요, 전자과 대학원 석사과정에 재학중인 고강욱입니다.
리뷰 잘 읽었습니다.
몇 가지 코멘트 남깁니다.
1. interactive segmentation이라는 분야 자체가 생소하여 첫 번째 figure가 있었다면 더 잘 이해할 수 있었을 것 같습니다.
2. method와 result 부분의 이미지 크기를 키우면 가독성이 더 나아질 것 같습니다.

감사합니다.

**Comment by gyuhyeonsim** [comment]
안녕하세요 다들 좋은 코멘트 감사합니다.
1.  수식이나 Figure 이슈는 해결 완료했습니다.
2. 어체는 제 의견과 논문 내용 정리를 구분하기 위해 분리하였습니다!
