### ISSUE TITLE
[2021 fall] ICCV 2021 MDETR - Modulated Detection for End-to-End Multi-Modal Understanding (20213510)

### ISSUE THREAD

**Issue by atjeong** [awesome-davian/awesome-reviews-kaist#115]

**Comment by GuilJung** [comment]
안녕하세요, 리뷰 잘 읽었습니다:)
읽으면서 든 생각을 몇 개 적어 보았습니다.

1. visual-linguistic multi-modal system 가 무엇인지 있으면 좋을 것 같아요
2. 몇개의 이미지가 너무 작아서 잘 안보여요
3. soft token prediction에서 관련성있는지 여부를 discrete가 아니라 continous하게 나타내는 이유가 있나요?
4. Evaluation metric 에서 정확도(accuracy)를 메트릭으로 사용하였다라고 되어 있는데 정확도에 대한 자세한 설명이 있으면 좋을 것 같아요. 단순히 질문에 대한 답을 맞췄는지 아닌지로 loss를 준 것인가요?

**Comment by hsrhee** [comment]
안녕하세요, 논문 요약 감사합니다.

**Method**

* "다시 말하면 어떤 query가 어떤 object에 해당되는 것인지 뚜렸하게 정해져 있지 않다" 오타 부분 공유드립니다.

**Experiment & Result**

* "커리큘럽 러닝을 사용하지 않았을 때는 성능상 손해를 봄을 실험적으로 확인하였다고 한다" 오타 부분 공유드립니다.

Downstream task (Visual Question Answering, ...) 각각에 대한 설명도 표와 같이 추가되면 이해하기에 더 좋아질 것 같습니다.

**Comment by heyzude** [comment]
안녕하세요, 제 리뷰를 읽어주셔서 감사합니다.
적어주신 커맨트들을 resolve해보려고 합니다.

GuilJung 님)
1 . "Visual-linguistic model (혹은 vision-language model, visio-linguistic model로도 불린다) 은 이미지와 텍스트 둘 다가 주어졌을때, 이 둘을 활용해 주어진 문제를 푸는 모델을 말한다. 예를들어 VQA(visual question answering) 문제의 경우, 쇼파에 앉아있는 사람들의 사진이 주어지고, '사진에 사람은 몇 명입니까?' 라는 질문이 텍스트 형식으로 주어졌을 때 모델은 사진과 텍스트를 입력으로 받은 후 알맞은 답을 도출해야 한다. Vision과 language, 두 개의 모달리티에 대한 모델이기 때문에 visual-linguistic multi-modal system 이라고 지칭하기도 한다." 부분을 추가하였습니다.
2. 이미지 사이즈를 수정하여 커밋을 했는데, 잘 반영될지는 모르겠습니다 (^^...!) 제가 의도한대로 깃북에서 렌더링을 하지 않더라고요 ㅎㅎ.. 만약 커밋 후에도 이미지사이즈가 작을 경우, 수정하여 추가로 커밋을 하겠습니다.
3. Soft token prediction 의 구현에 대해서 자세한 사항은 https://github.com/ashkamath/mdetr/issues/8 을 읽어보심이 가장 정확할 것 같습니다. 논문과 실제 코드 구현의 모양이 조금 다르게 보여서 저도 아는데까지 시간이 걸렸습니다. 제가 찾아보기로는, MDETR모델은 각 query(모델이 예측한 bbox라고 봐도 무방) 마다 관련이 있는 토큰들을 표시하는, logit을 출력하는데, 이 logit에 log_softmax를 취하면 BS x (num_queries) x (num_tokens) 행렬이 나옵니다. 이 행렬과, 이 행렬과 같은 사이즈의 실제 gt레이블의 행렬과의 Hadamard product 가 loss인 것이 바로 soft token prediction이라고 저는 이해했습니다.
4. Accuracy는 모델이 예측한 결과와 ground-truth label의 일치율입니다. 답과 logit 사이의 CELoss를 구하는 것으로 알고 있습니다.

hsrhee 님)
1. 오타 지적 감사합니다. 정정했습니다.
2. 네 간략한 설명을 추가했습니다.
