### ISSUE TITLE
[2021 fall] ICLR 2016 Unsupervised Representation Learning with Deep Convolutional Generative Adversarial Networks (20213751)

### ISSUE THREAD

**Issue by atjeong** [awesome-davian/awesome-reviews-kaist#116]

**Comment by LimGyeongrok** [comment]
안녕하세요 리뷰 잘 읽었습니다 :)
다음은 리뷰를 읽고 든 생각을 간략히 정리해보았습니다.

1. auto-encoder, GAN, RNN 등 다소 지식이 필요한 내용에 대해 링크를 걸어둔 점은 정말 좋은 것 같습니다.
2. 블랙방스 -> 블랙박스와 같이 오타를 수정해주시면 좋겠습니다.
3. Method 부분에 있는 Image (a), (b), (c), (d)가 각각 무엇을 의미하는지 간단하게라도 적어주시면 좋을 것 같습니다.
4. activation function을 generator에서는 ReLU를, output에서는 Tanh를 썼는데 이처럼 activation function을 다르게 써준 이유가 궁금합니다.

감사합니다.

**Comment by rlqja1107** [comment]
안녕하세요, 잘 읽었습니다. 이에 관련하여 개인적인 생각을 정리했습니다.
1. Related Work에서 관련 논문을 찾기 쉽도록 링크를 걸어놓은 Idea가 좋다고 생각합니다.
2.  Frechet Inception Distance(FID)가 주로 사용되어있다고 하는데, 이를 간략하게 설명하면 이해하는데 도움이 될 것 같습니다.
3.  De-duplication, Spatial Upsampling 등의 함축적인 용어에 대한 설명을 풀어서 쓰면 이해하기 쉬울 것 같습니다.

감사합니다.
