### ISSUE TITLE
[2021 fall] CVPR 2019 Improving transferability of adversarial examples with input diversity (20213189)

### ISSUE THREAD

**Issue by atjeong** [awesome-davian/awesome-reviews-kaist#117]

**Comment by tungnt101294** [comment]
Review of Diversity Input Method Article

1. Summary
    
    The author presents an implementation method for the paper titled **"Improving transferability of adversarial examples with input diversity"** by Xie *et al.* This paper focuses on Transferability of Adversarial  example by generating diverse input patterns.

2. Detailed Reviews
    
    Strengths:

      *  In general, the article is well organized and presented. It's easy to understand even for people who have not seen the paper, in my opinion.
      *  The author of the article (from this point on referred to as the author and not to be confused with the authors of the paper) provides a good summary for base knowledge on Adversarial attack, which helps the readers get a glimpse of what's described in the paper. 
      *  The author summarizes the method mentioned in the paper really well.
      *  The source code is open sourced on GitHub, which is a good sign. He/she also provides some instructions for implementing python venv.
      *  The code seems easy to understand and also well organized as well. Most of the packages used are very popular so it would not be difficult to reimplement.
      *  I really like the comments on the code as they help the readers understand much better and make it easier to follow.
      *  The raw outputs of the model are also included and briefly explained.
    
    Reviewer's Suggestions
    
      * While the introduction is well written, I think it is a bit rushed. The author could go right into the details of Adversarial attack without sufficient explanation for:

        * The contributions of the method and its impact. In my opinion, just a brief introduction and 1-2 examples would do the job.
        * A more friendly introduction into what adversarial attack is and its applications.
      * The Related work section should reference similar methods. It doesn't need to be very detailed but 1-2 should be mentioned.
      * It would be much better if the author provides the structure of the github repo. This could be done either in the article or in the summary of the repo.
      * A summary of the implementation is also needed. The author did mention a lot of details but they are somewhat scattered across the paper. Just a very short summary before the code would be more than enough.
      * I think a bit more explanation for the hyper-parameters is needed.
      * The objective of implementation a paper's algorithm is to mimic the results mentioned in the paper. So the author may want to spend more time on the results section to:
        * Draw some graphical illustrations of her results.
        * To compare her results to those of the paper and if there is some considerable discrepancy, give his/her insights on the possible reasons.
      * In my opinion, implementing a model always has some big challenges to connect the theory and implementation details. If the author has indeed faced some challenges, mentioning how he/she dealt with them would be wonderful.
3.

**Comment by KevinMIN95** [comment]
안녕하세요. 
작성해주신 글 잘 읽었습니다.

몇가지 보완하시면 좋을 것 같은 점 들입니다.

1. 전이 기반 적대적 공격 에 대한 설명이 부족합니다. 해당 분야에 배경지식 없는 상황에서 이해하기가 좀 힘든 것 같습니다.
2. 실험 결과를 표 등을 활용하여 정리해서 보여주면 좋을 것 같습니다. 
3. 해당 논문의 contribution이 **랜덤 크기 변환** 과 **랜덤 패딩** 을 적용했다 인건가요?? 해당 논문의 contribution 을 간단히라도 정리하면 좋을 것 같습니다. 

감사합니다.

**Comment by madin162** [comment]
Hi, I am Muhammad Adi.
I have read your english article about implementation code for Diversity Input method and I find it insightful.
Here are my feed backs for the article in more details:
1. The motivation and subject of the implemented algorithm is explained clearly with relevant related works. I think it would be great if citation for the related works is added to the article.
2. The implementation code is well documented and commented. However there are references to some file that is not hyperlinked yet, such as the env_di-fgsm.yml. Maybe in the final version the link to the github repo can be added.
3. More examples of the image produced from the algorithms is also nice to accompany the numerical result at the end of the article.

Overall it is a good structured article with clear codes. Hope my suggestions can help to improve it.

Thank you.
