### ISSUE TITLE
[2021 fall] CVPR 2020 Towards Better Generalization: Joint Depth-Pose Learning without PoseNet (20213594)

### ISSUE THREAD

**Issue by atjeong** [awesome-davian/awesome-reviews-kaist#118]

**Comment by rlgnswk** [comment]
안녕하세요 좋은 논문 리뷰 잘 봤습니다!
저는 문화기술대학원 석사과정 김기훈이라고 합니다.
해당 분야를 잘 모르는 입장에서 잘 이해되지 않았던 부분들 피드백 드립니다!

**Questions** 
1. 모델의 입력과 출력은 정확하게 무엇인가요?
2. Conclusion의 마지막에는 문장이 완성이 안됐던데, 누락된건가요?

**Opinions** 
1. RANSAC, 8-point algorithm 같은 기존 방법론을 설명하는 사진들이 있으면 더 좋을 거 같습니다.
2. 기존 연구 "with PoseNet"일때 보다 어떻게 좋아졌는지에 대한 부분이 보충되면 좋을 거 같습니다.
3. Related Works에 ICP regularization, dense online bundle adjustment 등의 방법에 해당하는 references있으면 좋을거 같습니다.

**Contents wanted to be added or removed**
1. 이미지가 입력으로 들어가서 어떻게 동작하는지, 어느 지점에서 loss가 계산되는지 더 자세하게 설명이 되면 좋을 거 같습니다.

감사합니다.
김기훈 드림.

**Comment by MBKwon** [comment]
안녕하세요. 기재해주신 리뷰 잘 읽었습니다.
아래의 정보가 추가되면 더 읽기 편할것 같아서 간단하게 의견 남겨봅니다.

- normalized 8-point algorithm과 RANSAC에 대한 링크 혹은 설명
- depth net과 flow net의 구성

감사합니다.

**Comment by bangjh0430** [comment]
안녕하세요. 전기및전자공학부 석사과정 방제현입니다.

리뷰에 대해서 몇가지 코멘트 남깁니다.

1. Title capitalization을 통일하면 좋을 것 같습니다. (e.g. "Overall System Architecture" <-> "Loss function")
2. 다른 분들께서 말씀해주신 것과 같이  normalized 8-point algorithm, RANSAC 등 알려진 기법에 대한 설명이 있으면 이해하는 데 도움이 될 것 같습니다.
3. Result에 대한 설명이 조금 더 있으면 좋을 것 같습니다. Visual odometry 결과를 나타내는 Figure 5의 경우에는 저처럼 해당 task에 대해 잘 모르는 사람이 보면 이 결과가 좋은 결과인지 아닌지 판단하기가 어렵습니다.

이상입니다.

리뷰 잘 읽었습니다! 감사합니다.
