### ISSUE TITLE
[2021 fall] NeurIPS 2017 Attention Is All You Need (20214355)

### ISSUE THREAD

**Issue by atjeong** [awesome-davian/awesome-reviews-kaist#119]

**Comment by jungyubaik** [comment]
이미지와 수식이 제대로 표현되지 않았습니다. 저자 정보도 수정되지 않았습니다. 시정 부탁드립니다.
이 논문의 핵심은 Transfomer라는 모델을 어떻게 구성했는지에 대한 Attention 기법이 갖는 구조적 특성이라고 생각합니다.
구조적 특성이 갖는 특징들에 대해 익숙치 않은 초심자들에게 친절한 설명이 더해졌음 합니다. 아래 링크 남겨드립니다. 감사합니다:)
https://wikidocs.net/31379

**Comment by bangjh0430** [comment]
안녕하세요. 전기및전자공학부 석사과정 방제현입니다.

리뷰에 대해서 몇가지 코멘트 남깁니다.

1. 수식 및 이미지가 제대로 표시되지 않습니다.
2. "~다."와 "~입니다"가 동시에 사용되고 있는데 하나로 통일해서 작성하시면 좋을 것 같습니다.
3. "Attention mechanism"의 title capitalization이 다른 제목의 title capitalization과 다릅니다. 통일성을 가지면 좋을 것 같습니다.

이상입니다.

리뷰 잘 읽었습니다! 감사합니다.

**Comment by JunJun0411** [comment]
안녕하세요. 
Naver Shopping AI Team 박준형입니다.

간단하게 리뷰를 작성하자면,

1. 수식에서 $ [수식] $ 을 -> $$ [수식] $$ 으로 수정하면 제대로 표기가 될 것 같습니다.

2. 이미지 또한 깨져서 보이지 않는데, 조교님들께서 남겨주신 템플릿을 참고해서 수정하면 좋을 것 같습니다. 

3. 유명한 논문인 만큼 **Problem definition**을 간단하게 적어주셨는데요. 처음 보는 사람들도 있을 수 있으니, 조금 더 쉽게 풀어서 설명해주시면 좋을 것 같습니다.

4. Attention mechanism에 대해서 수식을 통해 설명을 자세히 해주셨는데, Attention이 어떤 이유로 사용되는 것인지 어떤 점이 이전의 mechanism에 비해서 유리한 mechanism인지를 먼저 설명하면 좋을 것 같습니다.

5. **4.2.3** 소제목에 오타 있습니다.

정말 고생 많으셨습니다.
