### ISSUE TITLE
[2021 fall] NeurIPS 2020 Self-Supervised MultiModal Versatile Networks (20213808)

### ISSUE THREAD

**Issue by atjeong** [awesome-davian/awesome-reviews-kaist#125]

**Comment by junwoopark92** [comment]
1. 설명 중에 단락의 핵심 아이디어를 number item으로 정리 해주는 부분이 좋았습니다. 추가적으로 number item 별로 모델의 어떤 컴포넌트가 관련있는지 정리되면 읽기 더 편할듯합니다.

2. MultiModal learning의 결과를 이용한 application이나 쓰임새에 대해 간단히 설명해주면 더 좋을것 같습니다.

3. video에서 text, audio, image가 시간축으로 정렬되어 있을것 같은데 본문에 "The MMV approach requires no annotation or manual efforts to label video data, which is differentiated from previous work that relies on curated annotated datasets."  내용과 셋팅이 어떻게 다른지 궁금합니다.

**Comment by HATAEWOOK** [comment]
문화기술대학원 석사과정 하태욱(20214631)입니다
섹션별로 리뷰 작성하였습니다

## 1.Problem definition
- "조인트 임베딩"을 학습을 통해 얻을 수 있다는 것으로 이해했는데, 이 "조인트 임베딩"이 어떤 것이고, 어떻게 이용되는지도 함께 설명되면 좋을것 같습니다. 
## 4. Motivation
### Results
- 결과에 대한 그래프나 표가 있으면 이해하기 쉬울 것 같습니다.

**Comment by SeunghoonYang** [comment]
(한글 버전 리뷰)
안녕하세요,
카이스트 기계공학과 석사과정 20213361 양승훈입니다.

- 영문 버전 링크가 작동하지 않습니다.
- 윗 분들에게 언급이 되지 않을걸 보니 제 컴퓨터 문제 일수도 있을거 같은데, 수식 처리가 제대로 안되어 깨져보이는 현상이 있습니다.
