### ISSUE TITLE
[2021 fall] ICML 2019 Noise2Self Blind Denoising by Self-Supervision (20214653)

### ISSUE THREAD

**Issue by atjeong** [awesome-davian/awesome-reviews-kaist#126]

**Comment by HYUNMIN-HWANG** [comment]
You can see the post in here ([Eng verion](https://awesome-davian.gitbook.io/awesome-reviews/paper-review/2021-fall-paper-review/icml-2019-noise2self-eng)), ([Kor verion](https://awesome-davian.gitbook.io/awesome-reviews/paper-review/2021-fall-paper-review/icml-2019-noise2self-kor)). And [here](https://arxiv.org/abs/1901.11365) is the origin paper.

**Comment by MBKwon** [comment]
안녕하세요. 기재해주신 리뷰 잘 읽었습니다.
아래의 정보가 추가되면 더 읽기 편할것 같아서 간단하게 의견 남겨봅니다.

- 레이어 구성이나 동작 방식에 대한 간단한 설명이 있으면 이해가 편할듯 합니다

감사합니다.

**Comment by IamHanJungMin** [comment]
좋은 논문 리뷰 잘 읽었습니다. 감사합니다.
아래 코멘트를 남겨 드리오니 업데이트에 참고 부탁 드립니다.

- 서두의 '해당 논문에서는 clean한 이미지 없이 노이즈를 없애는 self-supervision 방식의 디노이즈 방법을 제안했습니다.' 문장에서 'Clean 한 이미지 없이'에 대한 배경 지식이 없는 사람 입장에서는 다소 어렵게 와닿을 수도 있을 것 같습니다. 그래서 바로 아래 섹션에서 잘 기술하셨던 내용을 참조하여 설명을 바꿔보면 좋을 것 같습니다. (예 : 'Clean 한 이미지 없이' -> '노이즈 특성에 대한 사전 학습 없이')
- Method 섹션에서 donut denoiser 와 classic denoiser의 비교를 진행하면서 왜 최종적으로 classic denoiser가 선정되었는지, 그리고 그것들이 기본 구조 신경망으로 사용된 Unet과 DnCNN과는 어떻게 연관지어질 수 있는지에 대해 조금 더 설명을 추가 해주시면 보다 매끄럽게 이해가 될 수 있을 것 같습니다.
- 독자들의 원리에 대한 이해를 돕기 위해 Reference & Additional materials 부분에 본 논문에 대한 강의 동영상을 링크해도 좋을 것 같습니다. 링크는 아래를 참조 부탁 드립니다.
  https://www.youtube.com/watch?v=jwp1MsSXOZ4
- 저자가 제시하는 아이디어 및 모델의 구동 원리에 대한 이미지를 추가하면 독자들이 보다 더 잘 이해하는데 더 도움이 될 것 같습니다. 위의 동영상에서 필요하신 이미지를 발췌해보실 수도 있을 것 같습니다.
- Markdown 서석의 수식 적용 오류에 대해서는 전반적으로 리뷰 해보실 필요가 있을 것 같습니다.

**Comment by IamHanJungMin** [comment]
좋은 논문 리뷰 잘 읽었습니다. 감사합니다.
아래 코멘트를 남겨 드리오니 업데이트에 참고 부탁 드립니다.

- 서두의 '해당 논문에서는 clean한 이미지 없이 노이즈를 없애는 self-supervision 방식의 디노이즈 방법을 제안했습니다.' 문장에서 'Clean 한 이미지 없이'에 대한 배경 지식이 없는 사람 입장에서는 다소 어렵게 와닿을 수도 있을 것 같습니다. 그래서 바로 아래 섹션에서 잘 기술하셨던 내용을 참조하여 설명을 바꿔보면 좋을 것 같습니다. (예 : 'Clean 한 이미지 없이' -> '노이즈 특성에 대한 사전 학습 없이')
- Method 섹션에서 donut denoiser 와 classic denoiser의 비교를 진행하면서 왜 최종적으로 classic denoiser가 선정되었는지, 그리고 그것들이 기본 구조 신경망으로 사용된 Unet과 DnCNN과는 어떻게 연관지어질 수 있는지에 대해 조금 더 설명을 추가 해주시면 보다 매끄럽게 이해가 될 수 있을 것 같습니다.
- 독자들의 원리에 대한 이해를 돕기 위해 Reference & Additional materials 부분에 본 논문에 대한 강의 동영상을 링크해도 좋을 것 같습니다. 링크는 아래를 참조 부탁 드립니다.
  https://www.youtube.com/watch?v=jwp1MsSXOZ4
- 저자가 제시하는 아이디어 및 모델의 구동 원리에 대한 이미지를 추가하면 독자들이 보다 더 잘 이해하는데 더 도움이 될 것 같습니다. 위의 동영상에서 필요하신 이미지를 발췌해보실 수도 있을 것 같습니다.
- Markdown 서식의 수식 적용 오류에 대해서는 전반적으로 리뷰 해보실 필요가 있을 것 같습니다.

**Comment by KanghoonYoon** [comment]
안녕하세요 산업및시스템공학과 박사과정 윤강훈 입니다.

Self-supervised 세팅에서 디노이징을 하는 방법을 제안한 흥미로운 주제에 대해서 다뤄주셔서 감사합니다. 특히 도넛 모양 window를 사용하는 것은 생각하지 못한 접근이어서 더 새로운 것 같습니다.

수정을 권고드리고 싶은 사항은,

많은 부분의 수식이 입력되지 않은 것 같습니다. 수식이 제대로 입력되지 않아 $가 그대로 노출된 부분이 많아 수정하시면 좋을 것 같습니다.

전통적인 방법과의 차이 (Introduction)
전통적인 방법과 어떤점이 다른지 Motivation 관점에서 설명을 더해주셨으면 합니다. J함수를 통해 독립적인 관계가 형성되는 것이 디노이즈를 하는 것에 대해서 어떤점이, 왜 좋아진 것인 지 이해하기 어려웠습니다. 그 부분을 보충해주시면 좋을 것 같습니다. 감사합니다.

감사합니다
