### ISSUE TITLE
[2021 fall] CVPR 2018 BlockDrop - Dynamic Inference Paths in Residual Networks (20213511)

### ISSUE THREAD

**Issue by atjeong** [awesome-davian/awesome-reviews-kaist#127]

**Comment by k97hyun** [comment]
안녕하세요. 산업및시스템공학과 석사과정 김현입니다.
기재해주신 리뷰 잘 읽었습니다. 좋은 리뷰 감사합니다.

리뷰에 대해 코멘트 남깁니다.
- 기존 논문의 결론의 이미지도 가져와 결과로 유추한 내용도 포함되어 있었으면 더 좋았을 것 같습니다.
- Framework가 그림으로 있었다면 이해하기 더 편했을 것 같습니다.

감사합니다.

**Comment by csleemooo** [comment]
안녕하세요.

리뷰 잘 읽어보았습니다. 관련해서 제 의견 간단하게 전달해드리겠습니다.
강화학습을 활용하여 residual block을 drop하는 최적의 구조를 찾는 방법이 새롭다고 느꼈습니다.

리뷰 관련해서는

1. problem definition이나 motivation을 좀 더 구체적으로 설명해주세요.
2. 논문 figure들을 추가해서 성능이 정확히 어떻게 달라졌는지 보여주는 것이 필요해 보입니다.
3. 결론에 본 논문에서 제안한 방법을 사용하면 속도가 빨라진다고 되어있는데, 얼마나 빨라지나요? table이나 그래프 결과가 있으면 좋을 것 같습니다.
4. 강화학습이 정확히 어떻게 적용됐는지에 대한 illustration이 있으면 좋을 것 같습니다.

감사합니다!
