### ISSUE TITLE
[2021 fall] MICCAI 2021 Federated Contrastive Learning for Volumetric Medical Image Segmentation (20204233)

### ISSUE THREAD

**Issue by atjeong** [awesome-davian/awesome-reviews-kaist#128]

**Comment by MBKwon** [comment]
안녕하세요. 기재해주신 리뷰 잘 읽었습니다.
아래의 정보가 추가되면 더 읽기 편할것 같아서 간단하게 의견 남겨봅니다.

- 주황색, 청록색, 노란색, 초록색 등의 영역으로 나눈 이유 알 수 있을까요?
- 사용된 encoder의 구조도 표현되면 이해하기 좋을듯 합니다 

감사합니다.

**Comment by jyh2378** [comment]
안녕하세요. 작성하신 리뷰 재밌게 잘 읽었습니다.
몇 가지 코멘트 및 질문 남깁니다.
- input이 volume의 형태로 표현되던데, 일반적인 이미지와는 다른 것인가요? 만약 다르다면 의료 영상 분야에서 다루는 입력 데이터의 형태는 일반적인 이미지와는 항상 다른건가요?
- 해당 논문이 타겟으로 하는 문제는 어떤 점인가요? classfication인가요? segmentation인가요? FL과 CL은 모두 학습 방법론에 대한 이야기 입니다. 우선 모델이 가지는 문제 구조에 대해 설명해주시면 이해하기가 더 좋을 것 같습니다.
- inline 수식이 깨지는 문제가 있습니다.

**Comment by gyuhyeonsim** [comment]
안녕하세요 리뷰 재밌게 읽었습니다 :)

1. figure 규격이 일정하면 가독성이 좋아질것 같습니다.
2. 문제 정의(Problem Definition)에서 해당 논문이 타겟하는 문제에 대해 자세히 기술해주시면 좋을듯합니다.
3. 결과 부분에서 분석적인 내용이 추가되면 좋을것 같습니다! figure만으로는 자세한 의미를 알 수가 없었습니다ㅠㅠ..
4. 별도로 해당 분야에 대해 전문적인 도메인 지식이 있으신것 같습니다! Supervised Learning 이용했을때보다 Federated Learning 사용했을때 얼마나 성능저하 문제가 발생하는지 적어주시면 큰 도움이 될것 같습니다ㅎㅎ
