### ISSUE TITLE
[2021 fall] CVPR 2021 Capsule Network is Not More Robust than Convolutional Network (20214412)

### ISSUE THREAD

**Issue by psh01087** [awesome-davian/awesome-reviews-kaist#130]

**Comment by pmh9960** [comment]
사진이 하나도 보이지 않음.

**Comment by daheekwon** [comment]
논문 요약 감사합니다. 아래는 제가 생각한 수정사항입니다. 

1) 위에서 언급하셨다시피 사진이 보이지 않습니다. 

2) Routing algorithm과 hebbian learning에 대해 간략하게라도 해주시면 내용을 이해하는데 도움이 될 것 같습니다. 
 - routing algorithm에 대해 실제로 그런 메커니즘은 존재하지 않는다고 하셨는데, 그게 정확히 무슨말인지 구체적으로 설명 부탁드립니다. 

3) 2. capsule network의 사고 실험 (T와 tilted T)에 대해서도 말로 이루어진 description보다 figure를 첨부하는게 훨씬 직관적일 것 같습니다. 

4) 이 논문이 말하고자 하는 주장/ contribution (capsule network의 한계점)을 글 서두에 정리해주시면 훨씬 읽을 때 더 편할 것 같습니다. 

감사합니다 :)

**Comment by pmh9960** [comment]
안녕하세요. 좋은 리뷰 감사합니다. Hinton에 대한 반박논문이군요.
아래는 제가 궁금한 내용을 적어봤는데 이에 대한 답변을 바탕으로 리뷰를 보완해주시면 감사드리겠습니다.

1. (마이너한 수정) 그림이 여전히 보이지 않습니다. 리뷰의 제목을 CapsNet으로 하면 안될 것 같습니다.
2. `인간은 '소파'라는 물체를 인식하기 위해서 수백 개의 소파를 모든 방향에서 관찰한 수만 장의 데이터를 필요로 하지 않기 때문이다.` 라는 문장이 저는 잘 동의하지 않는게 인간은 소파를 다양한 각도에서 비디오로 봤다고 생각하고 이는 수백장이 아니라 수 만, 수 억장을 본 것과 같은 효과라고 생각합니다.
3. `4. Discussion`에서 말씀하시는 `나`는 논문의 저자인가요? 리뷰어인가요?
4. 전체적으로 Dynamic Routing이 문제가 된다고 하니 Dynamic Routing에 대한 설명과 더불어 CapsNet에서 Hinton이 Dynamic Routing을 그렇게 구현할 수 밖에 없었던 이유를 설명해주시면 CapsNet 반박에 더 공감이 될 것 같습니다.

**Comment by khslily98** [comment]
안녕하세요.
작성해주신 글 잘 읽었습니다.  part-whole hierarchy 에 대한 개념을 처음 들었는데, 잘 정리된 리뷰 덕분에 새로운 사실을 알게되었습니다. 아래는 몇가지 보완하시면 좋을 것 같은 점 들입니다.

1. 저는 사진이 잘 보입니다! 수정해주셔서 감사합니다 :)
2. Capsule network의 전반적인 구조를 좀 더 꼼꼼히 설명해주시면 감사하겠습니다. "Capsule network를 어렵게 설명할 방법은 많지만 개념적으로는 단순하게 이해할 수 있다. 우선, 팔걸이의 존재 유무를 단 하나의 scalar value~~" 이라고 언급하시면서 어떤 상황에서 사용되는지를 설명해주신 부분은 좋습니다. 그런데 Capsule network의 그림을 첨부한 후 네트워크 구조에 대한 설명이 없이 계속 설명이 진행되니 그래서 Capsule network가 뭐지? 하는 의문이 듭니다.
3. 저도 다른 리뷰어님이 언급하신 것 처럼 'routing algorithm'과  'Hebbian learning' 이 잘 이해되지 않습니다.   Hebbian learning 이 capsule 단위로 작동한다는 의미가 잘 이해가 되지 않습니다. 자세한 과정이 이해가 되지 않는 것은 당연하다고 말씀하셨는데, 대충의 개념조차 이해하지 못했습니다. 그리고 캡슐 이라는 단어가 여기에서 사용되는데, 8~16개의 feature를 묶는다는 의미가 무엇인가요? 용어가 잘 이해되지 않아 이해에 부족함이 생기는 것 같습니다. 또한 캡슐과 capsule 의 용어를  통일해 주신다면 좀 더 통일성있는 리뷰가 될 것 같습니다.

감사합니다, 남은 학기 함께 화이팅해요!😊
