### ISSUE TITLE
[2021 fall] CVPR 2017 Densely Connected Convolutional Networks (20213267)

### ISSUE THREAD

**Issue by psh01087** [awesome-davian/awesome-reviews-kaist#131]

**Comment by daheekwon** [comment]
논문 요약 감사드립니다. 아래는 제가 생각한 수정사항입니다 :) 

1) 수식이 제대로 인코딩되지 않았습니다. $a$가 아닌 $$a$$로 바꿔야 합니다. 

2) 4. experiment & result  밑 가이드라인 글들 삭제 부탁 드립니다. 

3) publish된지 꽤 오래된 논문이기 때문에, 현재 다른 모델과의 성능비교 및 밝혀진 한계점 등에 대해서도 간략히 언급해주시면 좋을 것 같습니다.

감사합니다.

**Comment by jyh2378** [comment]
안녕하세요. 작성하신 글 재밌게 잘 읽었습니다.
1. 인라인 수식이 깨지고 있습니다. 해당 부분 고치면 가독성이 더 좋아질 것 같습니다.
2. 아직 미완인 부분이 빨리 작성되어야 할 것 같습니다.
