### ISSUE TITLE
[2021 fall] CVPR 2020 Meta-Transfer Learning for Zero-shot Super Resolution (20213279)

### ISSUE THREAD

**Issue by psh01087** [awesome-davian/awesome-reviews-kaist#132]

**Comment by sanmin0312** [comment]
안녕하세요.

리뷰 잘 읽었는데, 다만 모든 그림이 load되지 않아 이애하는데에는 어려움이 있었습니다.
따라서 정확한 코멘트를 드리기는 어렵지만 다음과 같이 코멘트 남깁니다.

- Problem Definition & Motivation은 그림이 없어도 이해가될 정도로 글을 잘 적어주셔서 읽기 편했습니다. 좋은 글 감사드립니다.
- related works를 SISR과 CNN 기반 방법으로 구성하셨는데 ZSSR이 CNN 기반 방법에 속하는 것인가요? 아니라면 ZSSR에 대한 설명이 추가되면 이해하는데 도움이 될 것 같습니다.
- Method 부터는 그림을 설명하는 위주로 구성을 해주셨는데 그림이 보이지 않아서 이해하는데 어려움이 있었습니다.

그림만 나온다면 좋은 리뷰가 될 것 같습니다.

**Comment by JunJun0411** [comment]
안녕하세요. 
Naver Shopping AI Team 박준형입니다.

이미지가 깨져 이해하기 어려웠습니다만, 간단하게 리뷰를 작성하겠습니다.

1. 우선 조교님들께서 남겨주신 템플릿을 참고해서 깨진 이미지들을 수정하면 좋을 것 같습니다. 

2. Motivation 첫문단 3번째 줄에 글이 약간 어색해서 이해하기 어려웠습니다. 
"사전에 미리 이용해놓고" 라는게 pre-trained 모델을 이용한다는 건가요? 

3. Meta-Transfer Learning에 대해 Method 중반부에 설명을 해주셨는데, Problem definition에서부터 자주 등장하는 단어이니 만큼 리뷰 초반 부분에 한 줄 정도로 요약해서 설명해주셨으면, Meta-learning, Meta-test 등의 단어가 나올 때마다 이해하기 더욱 쉬웠을 것 같습니다.

4. Method의 Meta-Transfer Learning 설명 문단 마지막 줄이 어색합니다. 중간에 수식(단어)이 빠진 걸까요?
"그리고 람다 파라미터는 사용해서 블러처리를 수행하기 위한 사용합니다"
바로 밑의 사진 밑의 줄에서도 어색한 부분이 존재합니다.
"Task-level Loss를 통해 model parameter 𝜃를 업데이트하**는 하고** Test error를 최소화하는 방향으로 optimization을 진행합니다."

- 마지막으로,
 Transfer Learning과 Meta Learning을 이용해 SR Task를 해결하는 **MZSR** 논문에 대해 전반적으로 잘 풀어서 설명을 잘 해주셨습니다. 이미지가 보였다면 더욱 좋았을 것인데, 살짝 아쉬웠습니다ㅠㅠ 이미지와 함께 수식, 단어(Keyword)가 빠져서인지 살짝 어색한 문장들만 수정하면 더 좋은 리뷰가 될 것 같습니다.
정말 고생 많으셨습니다 :) 👍

**Comment by k97hyun** [comment]
안녕하세요. 산업및시스템공학과 석사과정 김현입니다.
기재해주신 리뷰 잘 읽었습니다. 좋은 리뷰 감사합니다.

리뷰에 대해 코멘트 남깁니다.
- 이미지들이 제대로 보이지 않아 수정하면 좋을 것 같습니다.
- ZSSR에 대한 설명도 간단히 더 들어갔으면 좋았을 것 같습니다.

감사합니다.
