### ISSUE TITLE
[2021 fall] ECCV 2018 Object Detection in Video with Spatiotemporal Sampling Networks (20195590)

### ISSUE THREAD

**Issue by psh01087** [awesome-davian/awesome-reviews-kaist#134]

**Comment by rlgnswk** [comment]
안녕하세요 좋은 논문 리뷰 잘 봤습니다!
저는 문화기술대학원 석사과정 김기훈이라고 합니다.
작성하신 리뷰 보고 의견 남겨 드립니다.

**Typos**
Method에 **Spatiotemporal Feature Sampling.**, **Feature Aggregation.** 부분에 효과가 제대로 적용이 되지 않는듯 하네요.

**Opinion**
사진을 조금 더 크게 해주시면 보기 좋을 거 같습니다.

**Contents wanted to be added or removed**
1. Problem definition에 “이전 연구에서는 다양한 후처리 단계를 만들고..”라고 하셨는데, 어떤 방법이 였는지 설명해주시면 리뷰하신 논문의 contirbution이 더 잘 나타날 거 같습니다.

2. Related works에 Object Detection분야와 Deformable CNN부분이 해당 논문에 주요한 부분인데 설명이 아는 사람만 읽을 수 있는 설명인 거 같습니다. 좀 더 풀어서 설명해주시면 좋을 거 같습니다. 둘다 좋은 참조 사진들이 있는데 추가하면 이해하기 쉬울 거 같습니다.

3. Related works에 T-CNN, Seq-NMS, “Feichtenhofer가 제안한 방법” 등에 해당하는 reference가 있었으면 좋겠습니다. 그리고 해당 방법에 대해 약간의 설명이 있으면 전체적인 이해에 도움이 될 거 같습니다.

4. Result에 “광 흐름 감독”이라는 단어가 잘 이해되지 않습니다.

5. 2018년도 논문인데 그 이후 어떤 방향으로 발전했는지도 써주시면 좋을 거 같습니다. 

감사합니다.
김기훈 드림.

**Comment by YoonjinXD** [comment]
안녕하세요 AI 대학원 석사과정 정윤진 입니다.

1. 섹션 3 'Method' 에서 '기준 프레임 $I_t$에서 향상된 객체 감지 정확도를 위해 지원 프레임 $I_{t+k}$의 객체 수준 정보를 통합' 에 대한 추가적인 설명이 있으면 더 좋을 것 같습니다. 어떻게 통합하는지, 이로써 어떤 이점을 얻을 수 있는지에 대한 설명이면 좋을 것 같습니다.
2. 전체 STSN 모델은 완전히 미분될 수 있다고 설명 되어 있는데, 관련 수식을 첨부하여 미분 가능함을 보다 명확하게 보여주면 더 좋을 것 같습니다.
3. Result 섹션의 '광 흐름 감독' 은 Optical flow를 의미하는 걸까요? 몇몇 문장이나 단어들이 한국어로 직역되어 오히려 이해하기 어려운 것 같습니다.
4. Trivial issue이긴 하지만, Conclusion 섹션에 '본 연구가 기여하는 사항는 다음과 같습니다' 문장의 사항는 -> 사항은 으로 수정되어야 할 것 같습니다.

감사합니다.
정윤진 드림

**Comment by ksalsw1996DM** [comment]
안녕하세요. 이승우 입니다.
1. Spatiotemporal Feature Sampling 부분에 대한 설명이 살짝 애매한 것 같습니다. 다른 시공간에서 샘플된 블록이 STSN 아키텍쳐의 최종적인 output으로 추정되는데, 이 기능이 STSN 네트워크의 중간에 들어가는 부분에 대해서 좀 자세하게 설명해주시면 정말 감사하겠습니다.
2. Feature Aggregation이 두 부분에서 나타나는데(3, 4) 이부분이 실수이거나, 혹은 좀 다른 notation을 활용하였을것 같습니다.
3. 광 흐름 감독과 optical flow가 동일한지, 혹은 다른지 좀 혼동됩니다. 맥락으로는 동일해보이는데, 다른 용어를 활용한 이유가 있을까요? 만약 아니라면 수정하는게 review에 통일감을 주지 않을까 합니다.
감사합니다.

**Comment by IamHanJungMin** [comment]
안녕하세요. 여러분,

제 부족한 글임에도 불구하고 친절하게 리뷰 해주셔서 진심으로 감사드립니다.

심층학습 분야가 생소하여 많이 부족하지만 리뷰에 대한 수정 사항에 대해 최선을 다해 코멘트를 달아보았습니다. 내용 참고 부탁드립니다.



rlgnswk commented 14 days ago • 

안녕하세요 좋은 논문 리뷰 잘 봤습니다!
저는 문화기술대학원 석사과정 김기훈이라고 합니다.
작성하신 리뷰 보고 의견 남겨 드립니다.

**Typos**
Method에 **Spatiotemporal Feature Sampling.**, **Feature Aggregation.** 부분에 효과가 제대로 적용이 되지 않는듯 하네요.

=> 이 문제는 저도 어쩔 수 없는 것 같습니다. Typora 에서 다시 한번 확인해봐도 제대로 표시가 되는 것 같은데 Git 에서는 왜 안되는지 모르겠네요.

**Opinion**
사진을 조금 더 크게 해주시면 보기 좋을 거 같습니다.

=> 기존 이미지 사이즈를 약 130% 정도 확대했습니다.

**Contents wanted to be added or removed**

1. Problem definition에 “이전 연구에서는 다양한 후처리 단계를 만들고..”라고 하셨는데, 어떤 방법이 였는지 설명해주시면 리뷰하신 논문의 contirbution이 더 잘 나타날 거 같습니다.

   => "다양한 후처리 단계를 만들고" 라는 부분을 "시간에 따라 일관된 객체 탐지를 하는 단계를 만들고" 라고 변경하였습니다.

2. Related works에 Object Detection분야와 Deformable CNN부분이 해당 논문에 주요한 부분인데 설명이 아는 사람만 읽을 수 있는 설명인 거 같습니다. 좀 더 풀어서 설명해주시면 좋을 거 같습니다. 둘다 좋은 참조 사진들이 있는데 추가하면 이해하기 쉬울 거 같습니다.

   => Deformable CNN를 대표할 수 있는 이미지를 본문에 추가하였습니다. 말씀 주신 참조 사진들에 대해 알려주시면 감사하겠습니다.

3. Related works에 T-CNN, Seq-NMS, “Feichtenhofer가 제안한 방법” 등에 해당하는 reference가 있었으면 좋겠습니다. 그리고 해당 방법에 대해 약간의 설명이 있으면 전체적인 이해에 도움이 될 거 같습니다.

   => T-CNN, Seq-NMS, “Feichtenhofer가 제안한 방법” 등에 대한 레퍼런스를 추가하였습니다.

4. Result에 “광 흐름 감독”이라는 단어가 잘 이해되지 않습니다.

   => 우리말로 번역하기 어려운 단어들은 뜻을 훼손하지 않도록 본문에서 발췌하여 영어로 기입했는데 해당 항목은 누락된 것 같습니다. '광 흐름 감독' 이란 단어를 'Optical Flow Supervision'이란 단어로 변경하였습니다.

5. 2018년도 논문인데 그 이후 어떤 방향으로 발전했는지도 써주시면 좋을 거 같습니다.

   => 발전 방향에 대해 확인하실 수 있도록 주저자 정보에 대한 링크를 Reference & Additional materials에 추가하였습니다.



감사합니다.
김기훈 드림.



YoonjinXD commented 9 days ago

안녕하세요 AI 대학원 석사과정 정윤진 입니다.

1. 섹션 3 'Method' 에서 '기준 프레임 $I_t$에서 향상된 객체 감지 정확도를 위해 지원 프레임 $I_{t+k}$의 객체 수준 정보를 통합' 에 대한 추가적인 설명이 있으면 더 좋을 것 같습니다. 어떻게 통합하는지, 이로써 어떤 이점을 얻을 수 있는지에 대한 설명이면 좋을 것 같습니다.

   => 언급하셨던 '기준 프레임 $I_t$에서 향상된 객체 감지 정확도를 위해 지원 프레임 $I_{t+k}$의 객체 수준 정보를 통합' 부분을 '비디오 기준 시간 t에서의 기준 프레임 $I_t$에서 인근 프레임 $I_{t+k}$의 객체 정보를 감지에 활용함으로써 더 효율적으로 객체를 탐지할 수 있도록 하였습니다.'로 변경하고, 추가적인 설명을 위해 '그림 1과 같이 이미지에 비정상적인 포즈의 개체가 포함되어 있거나  Occlusion이 있는 경우, 해당 이미지 프레임과 시간상으로 인접해있는 프레임에 비교적 명확하게 보이는 동일한 개체가 비교적 표준적인 포즈로 포함되어 있다면, 개체를 더 잘 감지할 수 있도록 가까운 프레임의 정보를 활용할 수 있습니다. 본 논문에서는 객체 감지를 향상시키기 위해 K개의 선행 프레임과 K개의 후속 프레임을 참조 할수 있는 2K 지원 프레임을 사용합니다. ' 문구를 추가 하였습니다.

   

2. 전체 STSN 모델은 완전히 미분될 수 있다고 설명 되어 있는데, 관련 수식을 첨부하여 미분 가능함을 보다 명확하게 보여주면 더 좋을 것 같습니다.

   => '전체 STSN 모델은 완전히 미분될 수 있으므로' 라는 문구를 'STSN모델은 백본 네트워크로 사용한 ResNet-101 아키텍처를 기반으로 하는 Deformable CNN 모델을 사용하였기 때문에 완전히 미분될 수 있으므로'로 변경하였습니다. 미분 가능하다는 부분에 대해 관련 수식을 어떻게 첨부해야 할 지는 잘 모르겠습니다. 이 부분에 대해서는 추가적으로 조언주시면 감사하겠습니다.

3. Result 섹션의 '광 흐름 감독' 은 Optical flow를 의미하는 걸까요? 몇몇 문장이나 단어들이 한국어로 직역되어 오히려 이해하기 어려운 것 같습니다.

   => 우리말로 번역하기 어려운 단어들은 뜻을 훼손하지 않도록 본문에서 발췌하여 영어로 기입했는데 해당 항목은 누락된 것 같습니다. '광 흐름 감독' 이란 단어를 'Optical Flow Supervision'이란 단어로 변경하였습니다.

4. Trivial issue이긴 하지만, Conclusion 섹션에 '본 연구가 기여하는 사항는 다음과 같습니다' 문장의 사항는 -> 사항은 으로 수정되어야 할 것 같습니다.

   => 수정 하였습니다.

감사합니다.
정윤진 드림



ksalsw1996DM commented 2 days ago

안녕하세요. 이승우 입니다.

1. Spatiotemporal Feature Sampling 부분에 대한 설명이 살짝 애매한 것 같습니다. 다른 시공간에서 샘플된 블록이 STSN 아키텍쳐의 최종적인 output으로 추정되는데, 이 기능이 STSN 네트워크의 중간에 들어가는 부분에 대해서 좀 자세하게 설명해주시면 정말 감사하겠습니다.

   => 말씀하셨던 Spatiotemporal Feature Sampling에 대한 설명, '입력 참조 프레임을 조건으로 하는 주변 프레임에서 관련 기능을 샘플링하기 위해 시공간 샘플링 블록이 객체 수준 기능 맵에 적용됩니다. ' 에 대한 부분을, '시공간 샘플링 메커니즘은 주어진 비디오에서 시간 정보를 매끄럽게 통합하는 역할을 합니다. 이 샘플링 메커니즘은 예측 오프셋, 지원 텐서를 입력으로 사용하고 새로 샘플링된 피쳐 텐서를 출력하는 변형 가능한 4개의 컨볼루션 레이어를 사용하여 구현됩니다. 자세한 설명은 그림 2에 나와 있습니다. (그림 2에는 2개만 표시됨)' 으로 변경 하였습니다.

2. Feature Aggregation이 두 부분에서 나타나는데(3, 4) 이부분이 실수이거나, 혹은 좀 다른 notation을 활용하였을것 같습니다.

   =>실수였습니다. 2번째 'Feature Aggregation'을 'Object Detection'으로 수정했습니다.

3. 광 흐름 감독과 optical flow가 동일한지, 혹은 다른지 좀 혼동됩니다. 맥락으로는 동일해보이는데, 다른 용어를 활용한 이유가 있을까요? 만약 아니라면 수정하는게 review에 통일감을 주지 않을까 합니다.
   감사합니다.

   => 우리말로 번역하기 어려운 단어들은 뜻을 훼손하지 않도록 본문에서 발췌하여 영어로 기입했는데 해당 항목은 누락된 것 같습니다. '광 흐름 감독' 이란 단어를 'Optical Flow Supervision'이란 단어로 변경하였습니다.

**Comment by rlgnswk** [comment]
안녕하세요. Deformable Convolutional Networks 논문에 Figure 2 가 해당 컨셉을 가장 잘 나타낸거같아 추천드립니다.
