### ISSUE TITLE
[2021 fall] ICML 2019 HyperGAN - A Generative Model for Diverse, Performant Neural Networks (20218240)

### ISSUE THREAD

**Issue by psh01087** [awesome-davian/awesome-reviews-kaist#135]

**Comment by bo-10000** [comment]
### 서식 관련
- Author 정보가 누락되어 있습니다.
- Reference가 누락되어 있습니다.
- Method의 첫 문단이 영어로 되어 있습니다.

### 내용 관련
- Related work나 previous work 관련 내용을 추가해 주시면 좋을 것 같습니다. (Hypernetwork, normalizing flow 등)
- Result에 대한 설명도 추가해 주시면 좋을 듯 합니다 (Discussion)

**Comment by brightjade** [comment]
안녕하세요, 리뷰 잘 읽었습니다.

### Problem definition
- 여기 섹션에서는 HyperGAN 을 보여주시기보다 문제 정의를 해주셔야 할 것 같습니다. 먼저 무슨 문제를 풀고자 하는 지 모르니까 HyperGAN 피겨를 봐도 무엇을 하는지 와닿지 않습니다. 피겨는 method 섹션에 넣으면 좋을 것 같습니다.

### Motivation & related work
- Related work 에서는 이전 논문들을 언급 및 인용을 해주시면 좋을 것 같습니다.

### Result
- 결과 테이블과 피겨를 글로 설명해주시면 좋을 것 같습니다.
- ablation study 테이블은 없나요?
