### ISSUE TITLE
[2021 fall] CVPR 2017 Pyramid Scene Parsing Network (20213335)

### ISSUE THREAD

**Issue by psh01087** [awesome-davian/awesome-reviews-kaist#136]

**Comment by jhjun724** [comment]
안녕하세요 조천식 녹색교통대학원 석사과정 정현준입니다.
먼저 좋은 논문 리뷰 감사합니다.
PSPNet의 중요한 컨셉인 이미지 전체를 본다는 점과 이를 위해 네트워크에서 어떤 기법들을 사용했는지 (dilated convolution, pyramid pooling emd)를 자세히 알려준 부분이 좋았습니다. 그 외에도 네트워크의 하이퍼 파라미터 혹은 어떤 upsampling 방법이 사용됐는지 등의 네트워크를 구성하는 요소 하나하나를 자세히 설명해주는 느낌을 받았습니다.

자세히 설명된 논문리뷰이지만 추후에 보완될 리뷰에 개인적으로 추가되었으면 부분에 대해 코멘트 남깁니다.

1. Auxiliary loss에 대한 간단한 설명이 있으면 좋을 것 같습니다. Auxiliary loss 또한 다른 네트워크들의 back bone이 되는 classification 네트워크에서 가져왔기에, PSPNet의 경우 back bone이 되는 ResNet101의 중간단에서 나온 요소임은 알겠으나, 이를 semantic segmentation을 위한 loss로 활용하기 위해서는 기존의 feature를 decoder 단에서 upsampling 해주듯이 추가적인 과정이 필요할 것으로 생각됩니다. 이러한 부분이 간략하게나마 설명이 되었으면 좋겠습니다.

2. Deeplab을 많이 언급하셨는데 추후 PSPNet 리뷰를 통해 Deeplab을 접할 경우를 위해 같은 convolution이지만 PSPNet에서는 dilated convolution, Deeplab에서는 atrous convolution이라 불리는 점을 명시해두면 좋을 것 같습니다.

이미지가 누락되거나 수식이 잘못된 입력의 경우는 없는 것 같으며,
3.1 Pyramid Pooling Modul에서 e가 빠진 사소한 오타 하나정도 있는것 같습니다.

감사합니다.

**Comment by k97hyun** [comment]
안녕하세요. 산업및시스템공학과 석사과정 김현입니다.
기재해주신 리뷰 잘 읽었습니다. 좋은 리뷰 감사합니다.
Conclusion에 정리가 깔끔해서 이해하는데 도움을 받았습니다.

리뷰에 대해 코멘트 남깁니다.
- Related Work에서 SPP Net에 대한 설명이 조금 더 있었으면 좋았을 것 같습니다.

감사합니다.

**Comment by onejoon** [comment]
안녕하세요, 저는 AI대학원 박사과정 장원준입니다.
PSPNet의 각 구성요소 및 실험에 대해 세밀하게 설명해주셔서 좋았습니다. 디테일 코멘트는 다음과 같습니다.

1. Motivation-범주의혼동 설명에서 ground truth가 마천루이기 때문에 마천루가 빌딩으로 혼동된 것이 아닌지 궁금합니다.
2. 전체적으로 정보가 많아 중간에 주요 내용을 강조하면 더 가독성이 올라갈 것 같습니다.
