### ISSUE TITLE
[2021 fall] CVPR 2020 GPS-Net - Graph Property Sensing Network for Scene Graph Generation (20215550)

### ISSUE THREAD

**Issue by psh01087** [awesome-davian/awesome-reviews-kaist#137]

**Comment by fxnnxc** [comment]
GPS-Net 논문 리뷰 아티클에 대한 리뷰입니다.  전체적으로 Motivation부터 방법론, 실험까지 모두 짜임새있게 작성된 것 같습니다. 

몇가지 커멘트를 드리겠습니다. 

1. Problem Definition에서 V,E,R,O 중 R과 O가 무엇을 나타내는 지 설명을 추가하면 좋을 것 같습니다. 
2. Figure에 대한 설명에 initial이라는 문구가 적혀있는데, 제거하면 좋을 것 같습니다. 
3. 그림 3에서 기존에 사용된 모델과 차이에 대해서 설명할 때, Layer에 대한 설명은 있지만, 전체적인 모델에 대한 설명이 부족한 것 같습니다. 또한 구조를 적고 차이를 적는 부분에서 (a), (b), (c)에 대한 이해를 우선적으로 하고 설명하면 좋을 것 같습니다.

**Comment by indigopyj** [comment]
안녕하세요, 저는 카이스트 AI대학원 석사과정 박여정입니다.

1. problem definition에서 R,O는 어떤 의미인가요?
2. _Node Priority Sensitive Loss_ 이 부분에 효과가 적용이 안된 것 같습니다. 확인해보셔야될 듯 합니다.
3. Architecture 섹션의 Message Passing Network 들의 구조 (a), (b)와 제안된 DMP 구조 (c)를 설명하는 부분에서, 뭔가 네모박스 안에 써지는 효과는 없애는게 더 보기 좋을 것 같습니다. 스크롤바가 생겨서 불편하네요.
4. <MPNN Layer 에 direct 가 같이 도입되었다.> 이 부분에서 feature가 들어오는 방향과 그 방향에 따라 destination node의 업데이트정도가 달라진다고 이야기를 하고 있는데요, 그 "방향"이라는 것의 의미와 왜 그렇게 되는건지 이해가 어렵네요.
5. "반대로 gamma 작다 크다면" --> 이 부분이 뭔가 오타로 보입니다.
6. SGDET, SGCLS, PREDCLS 이 세가지 태스크에 대한 내용이 간단한 키워드형식으로만 적혀있어서 풀어서 써주시면 감사하겠습니다.
7. 현재 다양한 좋은 성능의 detector들이 개발되었음에도 불구하고, Faster R-CNN을 고집하는 이유가 있나요?


저에게는 다소 생소한 분야라서 한번에 이해하는 것이 힘들었는데, problem setting부터 모델이 어떤 부분에 포커스를 두고있는지를 찬찬히 잘 설명해주셔서 좋았습니다. 특히 로스 텀 설명부분은 다소 복잡할 수 있는데 말로 설명해주셔서 이해하기 쉬웠습니다. 다만 모델 구조부분은 위에서 말한 것처럼 이해가 안되는 문장들이 있어서 아쉬웠습니다.

**Comment by onejoon** [comment]
안녕하세요, 저는 AI대학원 박사과정 장원준입니다.
SGG task에 대한 설명이 직관적으로 잘 되어있고, 현존하는 모델의 문제와 GPS-Net이 개선하고자하는 방향이 명료하게 기술되어 있어서 좋았습니다. 다만 비전문가를 위해 SGG를 풀기 위한 기본 구조에 대한 설명이 들어가야 할 것 같습니다. 디테일 코멘트는 다음과 같습니다.

1. Problem definition에서 R,O에 대한 설명이 누락된 것 같습니다.
2. long-tail distribution에 대해 검색해보니, 빈번히 등장하지 않는 이벤트의 종류가 매우 많아 이를 무시하지 못하는 경우에 쓰는 표현인 것 같습니다. 따라서 standing in, feeding 같은 단어들이 비록 등장확률이 적음에도 이를 무시하지 않고 예측하는 것이 중요하다는 느낌으로 저자가 쓴 것 같습니다.
3. 이해를 돕기 위해 Graph R-CNN의 구조에 대한 설명이 추가되면 좋을 것 같습니다. (e.g. Union box의 역할이 무엇인지)
4. Message passing 설명할 때 사용하신 박스(?) 형태의 블록이 오히려 읽기 불편합니다.
5. Frequency Softening에서, Logsoftmax는 softmax에 비해 더 incorrect 패널티를 강조하는 것으로 알고있는데, 이는 등장빈도가 적은 long-tail triplets 예측에 방해되는 요소가 아닌지 궁금합니다.

**Comment by KanghoonYoon** [comment]
안녕하세요. Review 작성한 산업및시스템공학과 박사과정 윤강훈이라고 합니다. 말씀해주신 피드백은 감사히 리뷰에 반영하였습니다. 추가적으로, 리뷰에는 담을 내용이 아닌 질문들도 함께 남겨주신 것 같은데요.

1. 현재 다양한 좋은 성능의 detector들이 개발되었음에도 불구하고, Faster R-CNN을 고집하는 이유가 있나요?
이것은 모델의 공정한 비교 때문이지 않을까 합니다. SGDET, SGCLS, PREDCLS 3가지 태스크에 대해서 리뷰안에 설명을 드렸는데요. SGDET를 제외한 나머지는 순전히 SGG Method의 구조로 성능이 결정되게 됩니다. SGDET의 경우 Faster R-CNN을 통해 일관성을 준 상태에서, 성능을 비교한 것이라고 보입니다. 이렇게 설명하였지만 저 역시 이것에 회의적입니다. Detector의 발전과 함께, SGG에서 사용하는 Framework도 같이 향상되어야한다고 보기 때문인데요. 일단 현재로서는, 제대로 구축된 Framework도 확립되지 않아서, 실험의 편의성을 위해서 그랬다고 보입니다.

2. Frequency Softening에서, Logsoftmax는 softmax에 비해 더 incorrect 패널티를 강조하는 것으로 알고있는데, 이는 등장빈도가 적은 long-tail triplets 예측에 방해되는 요소가 아닌지 궁금합니다.

말씀해주신 log term은  Head Class의 값을 더 극명하게 크게 하게 되는데요.  말씀해주신 Term 뒤에, Logsoftmax가 어디 사용되어 있는지를 보면,  최종 예측 = 기존 예측 + d*Logsoftmax(p) 임을 확인하실 수 있을겁니다. 여기서 d가 positive라서, Head Class의 값을 더욱 극명하게 감소시켜주는 효과를 주는 것이라 보입니다. 따라서 Head class의 예측을 많이줄이고, Tail Class는 조금 줄임으로서, 둘의 balance를 맞췄다고 이해하시면 될 것 같습니다.

감사합니다
