### ISSUE TITLE
[2021 fall] ICCV 2019 Wavelet Domain Style Transfer for an Effective Perception-distortion Tradeoff in Single Image Super-Resolution (20213019)

### ISSUE THREAD

**Issue by psh01087** [awesome-davian/awesome-reviews-kaist#138]

**Comment by GuilJung** [comment]
안녕하세요, 리뷰 잘 읽었습니다:)

1. 이미지가 보이지 않습니다.
2. 수식들이 제대로 나오지 않는 것 같습니다.
3. PSNR, NRQM 지표에 대해 무엇을 평가한것인지 설명이 더 있으면 좋을 것 같습니다.
4. Loss에 대한 수학적인 설명이 있으면 좋을 것 같습니다. 
현재 연구분야에서 Adversarial loss와 MES loss의 trade-off를 조절하는 문제를 해결해야되는데 이 논문 아이디어가 어느정도 도움이 된 것 같습니다. 고맙습니다:)

**Comment by yoonjii** [comment]
친절한 설명 감사드립니다.
- Opinions or questions about the article
HR 이미지가 무엇인지 명확히 기재해주시면 좋을 것 같습니다.
loss들의 정의를 기재해주시면 내용 이해에 도움이 될 것 같습니다.
평가지표인 PSNR, NRQM, SSIM에 대한 추가 설명이 있으면 좋을 것 같습니다.

**Comment by heyzude** [comment]
안녕하세요, 리뷰 잘 읽었습니다.
몇가지 개선하면 좋은 점들이 있는데요,
1. 그림이 안 보여서, 전반적으로 설명에 대해 이해를 하기 어렵습니다.
2. 그림이 안 보이기 때문일수도 있는데, wavelet transform에 대한 자세한 설명이 필요해 보입니다. 또한 wavelet transform의 각 band 에 대한 설명도 필요하다고 생각합니다.
3. PSNR에 대한 설명이 있으면 좋겠습니다.
4. 적용하는 style-stransfer에 대해서 설명이 있으면 좋겠습니다.

감사합니다 :)
