### ISSUE TITLE
[2021 fall] ICML 2015 Show, Attend and Tell - Neural Image Caption Generation with Visual Attention (20214501)

### ISSUE THREAD

**Issue by psh01087** [awesome-davian/awesome-reviews-kaist#140]

**Comment by dudrrm** [comment]
안녕하세요, 양소영(20208207)입니다.


렌더링 이슈
1. 이미지가 github repo assets/34/ 에 업로드 되지 않은 것 같습니다. 이슈 수정 바랍니다.
2. 수식의 경우 $y$ 가 깃북에서 인코딩되지 않는데 $$y$$ 로 수정하시면 해결됩니다.


리뷰
* 전체적으로 이해가 잘 되었습니다. 문단의 구성 (e.g., section 3의 마지막 문단이 전부 인덴트됨)과 위의 이슈를 해결하면 좋은 글인 듯 합니다.

* Section 3: 
  * “Hard attention과 Soft attention”의 경우 attention의 값이 sum to 1 일 때 하나의 부분에 1을 몰빵하느냐, 여러 부분에 0.5, 0.2, 0.05, … 와 같은 식으로 attention score을 분포시키느냐의 차이로 알고 있고 이로 인해 발생하는 차이가 differentiable 한지/안한지 인 것 같은데요, 아마 아래 실험결과 부분에서 [Fig.2](https://intellipaat.com/community/19848/soft-attention-vs-hard-attention)  를 설명하셨을 텐데 이 부분을 가져오시면 이해가 잘 되지 않을까 싶습니다.

* Section 4: Experiment
  * dataset, evaluation metric에 대한 간단한 설명이 있으면 좋을 것 같습니다. 예시 이미지나, 데이터셋에 접근 가능한 링크가 연결되면 어떨까요?

* Section 5: Conclusion
  * 리뷰가 많이 된 논문으로 알고 있는데, 근래에는 어떻게 활용되고 있으며 참고할만한 블로그나 논문을 리스트업해서 정리해주시면 논문 리뷰 전반 퀄리티가 높아질 듯 합니다.

**Comment by indigopyj** [comment]
안녕하세요 저는 카이스트 AI 대학원 석사과정 박여정입니다. 

1. 이미지 경로를 "../../.gitbook/assets/author_id/file_name.jpg" 으로 수정하셔야됩니다. 수식과 이미지가 제대로 보이지 않으니 글을 이해하는데 다소 힘들었습니다.
2. **Attention: Stochastic hard vs Deterministic soft ** 이부분에 볼드체 효과가 반영되지않았네요. 확인하셔야될 것 같습니다.
3. soft attention과 hard attention에 대해서 보다 더 자세하게 설명해주시면 좋을 것 같습니다. 그리고 왜 differentiable한게 좋은건지도 궁금합니다.
4. image captioning에서 굉장히 유명한 논문인걸로 알고있는데, 생각보다 내용이 간단해서 아쉬웠네요. 특히 어텐션 개념이 쓰였다는것이 포인트인데, 어텐션 논문 내용을 참고해서 어텐션에 대해서도 자세히 다루면 좋을 것 같습니다.

**Comment by bulsajyo** [comment]
-안녕하세요 기계공학과 박사과정 오상윤(20215201) 입니다.
먼저 논문 리뷰 잘 읽었습니다.
이미지나 수식 이슈들에 대해서는 이미 위 두 분께서 충분히 코멘트를 주셔서 따로 언급하지 않겠습니다.
1. Reference 에 리뷰하신 논문과 리뷰에서 언급하신 다른 논문들에 대해 적어주시고 본문에서도 reference에 대응하는 번호 달아주시면 좋을 것 같습니다.

2. Related work에서 다른 논문들과 비교할때 다른 모델들의 간략한 모델 아키텍쳐 설명이 있으면 좋을 것 같습니다.

3. Conclusion에 리뷰의 요약, result의 해석, 한계점이 언급되면 좋을 것 같습니다.
