### ISSUE TITLE
[2021 fall] ECCV 2020 Conditional Sequential Modulation for Efficient Global Image Retouching (20218197)

### ISSUE THREAD

**Issue by psh01087** [awesome-davian/awesome-reviews-kaist#142]

**Comment by yujin05** [comment]
안녕하세요, 저는 전기 및 전자공학부 석사과정 이유진(20213472) 입니다.

사진 보정과 관련한 연구에 대해서는 처음 접해보았기 때문에 굉장히 흥미롭게 읽었습니다. 

[수정사항]
Motivation 부분에서 무엇을 말씀하시려고 하는것인지 정확하게 파악이 되지 않습니다. 무엇이 동치인 것인지, 그리고 정확히 MIT-Adobe FiveK dataset을 만들 때 사용한 global operation이 무엇을 말하는 것인지 등에 대해서 파악하기가 어려웠습니다.

수식이 정확하게 되어있지 않아서 보는데 불편함이 있어 정확한 수식이 나오게 수정해주시면 좋을 것 같습니다.

그리고 Illustration에서 pixel level과 space level의 network가 그냥 동일한 network인데 pixel-level은 픽셀 하나가 어떤 식으로 진행이 되는지, 그리고 space-level은 그냥 전체적으로 보여주는 것이 맞는지 궁금합니다.

**Comment by mjbooo** [comment]
안녕하세요 AI대학원 석사과정 이민재(20214501) 입니다. 

하드웨어 차이로 설명될 수 없는 사진의 차이(예컨대 갤럭시 vs. 아이폰)에 대해서 궁금했어서, on device 이미지 보정을 알 수 있어 좋았습니다. 

1. 전반적으로 번역체라는 느낌을 받는데, 문장 내 주술 호응을 조금 수정해주신다면 읽기 훨씬 수월할 것 같습니다. 예컨대 Motivation 부분에서  '사진 보정에 주로 사용되는 함수들을 이미지의 픽셀 별 1x1 convolution과 이미지 전체에 동일하게 영향을 주는 Global Feature Modulation(GFM)을 이용하여 동치임을 보였다' 같은 문장에서 그렇게 느꼈습니다. 

2. Method 부분에서 인라인 수식 삽입 문제는 윗분이 말씀해주신 것 같고, conv와 GFM으로 대체하려는 각 함수가 왜 필요한지를 알려주기 위해  함수 적용 전/후 사진을 대비시킨다면  독자에게 더 명징하게 알려줄 수 있을 것 같습니다. 

3. local/global artifact 등 domain specific할 수 있는 용어들에 별다른 설명이 붙어있지 않아 조금 읽기 힘들었습니다. 

4. pixel/space level figure부분에 대해 두방식이 어떻게 다르고 왜 그런차이가 나오는지 설명하면 훨씬 읽기 수월할 것 같습니다. 

정성들인 논문 리뷰 감사합니다!

**Comment by pmh9960** [comment]
네 안녕하세요 20218197 AI대학원 박민호입니다. 두 분 모두 리뷰해주셔서 감사합니다.

@yujin05 
> 안녕하세요, 저는 전기 및 전자공학부 석사과정 이유진(20213472) 입니다.
> 
> 사진 보정과 관련한 연구에 대해서는 처음 접해보았기 때문에 굉장히 흥미롭게 읽었습니다.
> 
> [수정사항] Motivation 부분에서 무엇을 말씀하시려고 하는것인지 정확하게 파악이 되지 않습니다. 무엇이 동치인 것인지, 그리고 정확히 MIT-Adobe FiveK dataset을 만들 때 사용한 global operation이 무엇을 말하는 것인지 등에 대해서 파악하기가 어려웠습니다.
> 
> 수식이 정확하게 되어있지 않아서 보는데 불편함이 있어 정확한 수식이 나오게 수정해주시면 좋을 것 같습니다.
> 
> 그리고 Illustration에서 pixel level과 space level의 network가 그냥 동일한 network인데 pixel-level은 픽셀 하나가 어떤 식으로 진행이 되는지, 그리고 space-level은 그냥 전체적으로 보여주는 것이 맞는지 궁금합니다.

1. 제가 다시 보았는데 motivation에서 method를 너무 설명하려고 한 것 같네요. method를 설명하려는 부분은 method section에 link를 걸어두었고 좀 더 읽기 쉽도록 바꿔보았습니다.

2. 말씀하신대로 global operation에 대해서 상당부분 불친절하게 느끼셨을 것 같습니다. 그래서 아래와 같은 문장을 본문에 추가하였습니다.
    > (e.g., brightness, contrast 변화 등 adobe lightroom 내장 함수를 이용하여 이미지 내 모든 픽셀에 영향을 주는 operations)

3. In-line 수식에 대해 고쳐보려고 노력하였는데 아무래도 gitbook에서 지원하지 않는 것 같습니다. 반영해드리지 못해서 죄송합니다.

4. Pixel level과 space level은 말씀하신대로 동일한 네트워크입니다. 제가 review에도 작성한 것 처럼 단지 정성적으로 어떻게 사진 보정 작업이 1x1 conv로만 가능한지 조금이나마 더 이해가 될 수 있도록 추가한 것 같습니다.  아무래도 이전까지는 이 분야에서 3x3 conv만을 사용하다보니 1x1 conv로도 충분히 가능하다는 contribution을 최대한 설명하려고 노력한 것 같습니다.

@mjbooo 

> 안녕하세요 AI대학원 석사과정 이민재(20214501) 입니다.
> 
> 하드웨어 차이로 설명될 수 없는 사진의 차이(예컨대 갤럭시 vs. 아이폰)에 대해서 궁금했어서, on device 이미지 보정을 알 수 있어 좋았습니다.
> 
> 1. 전반적으로 번역체라는 느낌을 받는데, 문장 내 주술 호응을 조금 수정해주신다면 읽기 훨씬 수월할 것 같습니다. 예컨대 Motivation 부분에서  '사진 보정에 주로 사용되는 함수들을 이미지의 픽셀 별 1x1 convolution과 이미지 전체에 동일하게 영향을 주는 Global Feature Modulation(GFM)을 이용하여 동치임을 보였다' 같은 문장에서 그렇게 느꼈습니다.
> 2. Method 부분에서 인라인 수식 삽입 문제는 윗분이 말씀해주신 것 같고, conv와 GFM으로 대체하려는 각 함수가 왜 필요한지를 알려주기 위해  함수 적용 전/후 사진을 대비시킨다면  독자에게 더 명징하게 알려줄 수 있을 것 같습니다.
> 3. local/global artifact 등 domain specific할 수 있는 용어들에 별다른 설명이 붙어있지 않아 조금 읽기 힘들었습니다.
> 4. pixel/space level figure부분에 대해 두방식이 어떻게 다르고 왜 그런차이가 나오는지 설명하면 훨씬 읽기 수월할 것 같습니다.
> 
> 정성들인 논문 리뷰 감사합니다!

1. 말씀하신대로 Motivation이 문장을 고쳐보았습니다. 하지만 이 논문이 유명한 분야가 아니라 잘 알려져 있지 않아 어디서 한글은 물론 영어 블로그도 없기에 어디서 긁어온 것은 아니라고 말씀드리고 싶습니다. 번역체는 그냥 제 문장력이 처참했던 것입니다... ㅠㅠ 

2. in-line 수식은 위에 분께 말씀드린 것처럼 gitbook에서 잘 지원하지 않는 것 같습니다. alpha를 inline에서 표현하고 싶은데 어떻게 해야할 지는 잘 모르겠네요.

3. Global/Local artifact에 대해서 본문에 구체적인 설명과 더불어 qualitative result를 채워 넣어 보았습니다. 하지만 이 두 장의 사진에서는 지금 다시보니 아주 명확하게 local artifact가 보이지는 않네요.

4. 윗 이유진님이 말씀해드린 내용과 같이 pixel/space level figure는 서로 다른 네트워크가 아닌 1x1 convolution을 더 잘 설명하기 위한 figure라고 해석하고 보시면 될 것 같습니다. 두 분 모두 헷갈리신 것 같은데, 이에 대한 정확한 설명도 추가하도록 하겠습니다.
