### ISSUE TITLE
[2021 fall] ICML 2020 Frustratingly Simple Few-Shot Object Detection (20205665)

### ISSUE THREAD

**Issue by psh01087** [awesome-davian/awesome-reviews-kaist#143]

**Comment by quangbk2010** [comment]
Hello, this is Quang.
It's my pleasure to review your paper review.

Overall, I think it's a detailed review.
There are some minor adjustment maybe considered.

1. I don't really get why finetuning only the box classification and regression networks helps with only small training set in the finetuning step. Could you please explain more about this idea?
2. What is 'intra-class variance' showed in Method section?
3. The images maybe need to be bigger. I think when you edit it on Typora, it fits, but not with gitbook.
4. $$ $$ should be used for mathematical formulas.

If there is any misunderstanding, please correct me.
Thank you.

**Comment by sateodoro** [comment]
Hello! I am Samuel Teodoro (20218258). Here are a few comments:

- Equations are not displayed properly.
- Figure 1 and Table 1 are too small.

**Comment by pranjay-unof** [comment]
Hello, I am Pranjay Shyam (20185586) the reviewer assigned for this paper review. 

I would like to summarize the areas of revision as,

- The equations are not formatted properly. 
- Image scaling can be considered to ensure proper consistency. Specifically Table 1 and Fig 1 are hard to read.
-  Table 4 is scaled excessively

The overall content of the review is good, covering all the critical aspects such as problem definition, motivation and experiments.

**Comment by madin162** [comment]
Thank you for all the constructive feed backs.  I have adjusted the article according to the comments by adjusting the image and table scales, correcting the equations, and adding some additional information for clearer explanation.

Hope my article review can give some benefit to you as the reviewer.
