### ISSUE TITLE
[2021 fall] CVPR 2021 Center-based 3D Object Detection and Tracking (20204450)

### ISSUE THREAD

**Issue by psh01087** [awesome-davian/awesome-reviews-kaist#145]

**Comment by HYUNMIN-HWANG** [comment]
안녕하세요. AI 대학원 석사과정 황현민입니다.
아래 논문 리뷰에 대한 코멘트 남깁니다.

**Typos**
- CenterNet, Result 에 있는 이미지들이 안 보입니다.
- 본문 안에 있는 수식 들이 $ --- $ 이런 식으로 깨져서 보입니다.

**Opinions or questions about the article**
- Idea 부분에서 해당 논문은 anchor-based 방식이 아닌 center-based를 제안했다고 했는데, 여기서 anchor-based 방식이 어떤 것인가요? 위 CenterNet 부분에 적힌 기법들을 anchor-based 방식이라고 하는 건가요? 

**Contents wanted to be added or removed**
- Centerpoint에 사용된 딥러닝 모델에 대해 더 설명해주시면 좋을 것 같습니다. 특히 Centerpoint에 사용된 3D Backbone은 어떤 모델을 사용한 것인가요? 그리고 reference에 Fast RCNN 논문을 참고하셨는데 Centerpoiont에 어느 부분이 Fast RCNN을 사용한 부분인지 궁금합니다.

감사합니다.

**Comment by baeseongsu** [comment]
안녕하세요, 배성수입니다.
재밌는 논문 소개해주셔서 감사합니다.

해당 Paper Review를 읽으며 몇 가지 생각난 피드백을 전달드립니다.
- 이미지와 수식들이 일부 깨지는 부분이 있는 것 같습니다.
- Problem Definition 부분에서 큰 핵심 개념을 잘 요약해주신 것 같습니다. 2D object detection과 3D object detection의 차이를 보여주는 illustrated sample이 있다면, 보여줘도 좋을 것 같습니다.
- 해당 방법론인 CenterPoint의 Qualitative sample이 있다면, 간략하게 소개해주셔도 좋을 것 같습니다.

감사합니다.
