### ISSUE TITLE
[2021 fall] NeurIPS 2020 Meta-Learning Requires Meta-Augmentation (20215427)

### ISSUE THREAD

**Issue by psh01087** [awesome-davian/awesome-reviews-kaist#146]

**Comment by povolann** [comment]
Hi, I'm Anna Povolna (20205678) and here is my comment on your review.

### Overall Review
- I think that the reviewed paper is not included in the References.
- I think it would be much better if the author would actually rewrite the content of the reviewed paper in his own words. A huge part of the review is just copy-and-pasted.
- There are actually not that many grammar mistakes, just a few.

#### Common grammar mistakes
- Check the commas in sentences.
- Check articles before nouns.

#### Consider rewriting this part

- _Meta-augmentation avoid both by shuffle classes in classification and add a random variable to y in regression._
   - "Meta-augmentation avoids both by shuffling classes in classification and adding a random variable to y in regression."

**Comment by KevinMIN95** [comment]
Hi, here are my reviews on your post

1. The figures are too small to see. 
2. It would be better if you explain more about meta-learning ( in the introduction section)  for those who are first in this area. Maybe, adding figures helps a lot to understand.

Thanks.
