### ISSUE TITLE
[2021 fall] CVPR 2017 Photo-Realistic Single Image Super-Resolution Using a Generative Adversarial Network (20218258)

### ISSUE THREAD

**Issue by psh01087** [awesome-davian/awesome-reviews-kaist#148]

**Comment by johnlee92** [comment]
I'm Jaehyeon Lee working at NAVER corporation.
Thank you for your great review. I can get a lot of insights.
I gave you some comments below about the review.

1. It is interesting that using content loss for 'Perceptual Loss'
2. Appropriate images and explanations are provided
3. It would be better if it contains explanations about PSNR and SSIM metrics.

Thank you.

**Comment by yujin05** [comment]
I'm Yujin Lee (20213472) from electrical engineering.
I'm glad to read more about super resolution, one of my interesting field.
There are some comments about your review.

[Comments]
-More explanations or figures about the reason why PSNR and SSIM are not sufficient would be needed.

-It would be better if you add some basic concept or goal of generator and discriminator

Thank you

**Comment by junhahyung** [comment]
I'm Junha Hyung (20218240) from graduate school of AI.

Thank you for sharing very famous and important work on super-resolution.
The review is mostly well-written, but I suggest two improvements that could possibly make it better.

1> It would be better if you explained little more about the "sub pixel layer". How does the generator perform upsampling?

2> VGG loss is not clear. Is it used together with the perceptual loss? 

Thank you:)
