### ISSUE TITLE
[2021 fall] IEEE 2019 Densely Residual Laplacian Super-Resolution (20215201)

### ISSUE THREAD

**Issue by psh01087** [awesome-davian/awesome-reviews-kaist#150]

**Comment by rlqja1107** [comment]
안녕하세요, 리뷰 읽고 개인적인 생각을 정리하겠습니다.
1. Figure 3의 사진을 좀 더 선명하면 보기 좋을 것 같습니다.
2.  Laplacian Attention 부분에서 마지막에 설명이 끊겨있는 것 같습니다. 여기에서 보충해서 더 설명해주시면 이해가 쉬울 것 같습니다.
3.  Compression Unit을 보면서 어떻게 작동하는지 알 수 있을까요?
4.  Method에서 Overall Architecture를 확대하면 보기 쉬울 것 같습니다.
5.  Laplacian Attention이 중요한 것처럼 보이는데, 수식 부분이나 설명이 부족하다고 생각합니다.
감사합니다.

**Comment by dkmv0623** [comment]
안녕하세요, 리뷰 잘 읽었습니다.

몇 가지 코멘트 남깁니다.

1. Related Work 부분에 이해하기 어렵거나 제가 파악한 바와 조금 다른 부분들이 있습니다. (ex, 첫 문장의 표현상 SRCNN이 복잡한 구조를 가지고 있다고 읽힐 수 있을 것 같습니다. RCAN 또한 매우 복잡한 구조를 가지고 있지는 않은 것 같습니다. 문장들을 전체적으로 조금만 더 풀어서 써주시면 이해하기 쉬울 것 같습니다.)
2. Motivation - Idea 부분의 1번에서, 저해상도의 정보를 충분히 이용하고자 하는 것은 모든 SISR 모델들이 공통적일텐데, 어떻게 정보를 더 잘 이용하는지가 궁금합니다. 또한 3번에서, 모델과 feature 사이의 의존도를 학습한다는 것이 어떤 의미인지 궁금합니다.
3. 저장 실수인지 Laplacian attention에 대한 설명이 미완성되어 있습니다.
4. 실험 Setup 부분의 가독성이 조금 떨어지는 것 같습니다.
5. 결론에서, 네트워크가 고해상도와 중간 해상도의 정보를 학습한다는 것이 어떤 의미인지 조금 더 설명해주시면 좋을 것 같습니다.
6. 결론의 2번에서, 밀접하게 연결한다는 번역 보다는 dense하게 연결하였다는 표현이 이해하기 더 쉬울 것 같습니다.

감사합니다.

**Comment by csleemooo** [comment]
안녕하세요.

리뷰 잘 읽어보았습니다. 관련해서 제 의견 간단하게 전달해드리겠습니다.

1. Related work에서 "parameter수는 감소하더라도 총 연산량은 증가하게되는 문제를 갖고있다"고 하셨는데, 이 부분에 대해 조금 더 자세하게 설명해주세요
2. Figure 1의 형식이 잘못 된 것 같습니다.
3. Laplacian attention에 대해 좀 더 자세한 설명이 필요해 보입니다. 저장도 미완성 형태로 된 것 같습니다.
4. 결과에 대한 해석을 좀 더 자세히 써주시면 좋을 것 같습니다.
5. Long skip connection, short skip connection, local connection, deep supervision 등과 같은 내용을 결론에서 보았지, 앞서서 보지 못했습니다. Method의 빠진 부분에 대해 좀 더 설명 써주세요.
6. Figure 5에 파라미터 수에 대한 그래프가 있는데, 본 논문에서 파라미터 수도 중요한가요? 어떤 context에서 나왔는지 설명해주면 좋을 것 같습니다.

감사합니다.
