### ISSUE TITLE
[2021 fall] ICMV 2017 Classification of Time-Series Images Using Deep Convolutional Neural Networks (20208061)

### ISSUE THREAD

**Issue by psh01087** [awesome-davian/awesome-reviews-kaist#151]

**Comment by sanmin0312** [comment]
안녕하세요. 카이스트 녹색교통대학원 김산민입니다.
작성해주신 리뷰 잘 읽었습니다.

전체적으로 깔끔하게 잘 설명해주셔서 많은 도움이 되었습니다.
몇가지 코멘트들을 아래 적어놓았으니 수정하실 때 참고해주시면 감사하겠습니다.

### comments
- 3.Method에서 모델 구조를 글로 설명해주셨는데 그림이 있으면 더 이해하기 편할 것 같습니다.
- 4.Experiment & Result에서 비교대상들(1-NN DTW 등)에 대해서도 간단한 설명이 있으면 더 좋을 것 같습니다.
- RP를 related works로 설명해주셨는데, 그렇다면 이 논문에서 제안하는 방법의 contribution은 무엇인지 잘 모르겠습니다. 기존에 존재하는 RP를 활용해 시계열 데이터에 CNN을 적용해보았다 인가요?
- "우상단은 적색은 가까운 시간내의 궤도간의 차이가 심하다는것을 의미하며 우하단은 시간적으로 먼 궤도간의 차이가 심함을 나타내게 됩니다." 이라고 적어주셨는데 행렬의 대각성분과 가까이있는 위치의 성분이 적색일수록 시간적으로 가까운 궤도간의 차이가 심하고 대각성분과 먼 성분이 적색일수록 먼 시간의 궤도차이가 심한 것 아닌가요? 

### typos
- problem definition에서 수식 깨짐
- motivation에서 "수평 혹은 수평" -> "수평 혹은 수직"?

**Comment by brightjade** [comment]
안녕하세요, 리뷰 잘 읽었습니다.
시계열은 익숙치 않다보니 감안해서 제 코멘트들을 봐주시면 감사하겠습니다.

### Related Work
- 여기서 수식이 조금 헷갈립니다. $R_{i,j}$ 를 정의하는 수식인 것 같은데, 처음에 x 와 s 를 먼저 정의하는 게 가독성에 방해가 되는 것 같습니다. (+ x 랑 s 도 정의가 글로 되어 있지 않아서 뭔지 헷갈립니다.)
- "l길이의 시계열은..." 에서 l 이 L 인지 i 인지 헷갈립니다. mathmatical l (엘)로 바꾸는 게 좋을 듯 합니다.
- 이 논문 이전 논문들은 어떻게 풀어왔는지 궁금합니다. 이전 논문들을 간략하게라도 언급하시면 좋을 것 같습니다.

### Method
- 모델 그림이 있으면 좋을 것 같습니다.

### Result
- 결과표가 직관적이지 않아 보고 바로 이해하기 어렵습니다. 최대한 말로 풀어주시면 좋을 것 같습니다. N_tr, N_te 등 무엇을 뜻하는지, 점수도 table caption 에 무엇인지 써있지만 좀 더 자세히 설명해주시면 좋겠습니다.
