### ISSUE TITLE
[2021 fall] ECCV 2020 Tracking Objects as Points (20205047) 

### ISSUE THREAD

**Issue by niceDuckgu** [awesome-davian/awesome-reviews-kaist#152]

**Comment by jungyubaik** [comment]
아주 친절한 설명과 사진들로 인해 읽기 너무 편했습니다. 
같은 분야에 관심을 가진 학생으로서 정말 감사드립니다:)
논문 리뷰를 읽으면서 아주 많은 공부가 되었습니다.
'greedy matching이라는 가장 간단한 방식의 매칭을 사용했다는 점에서 앞으로 개선할 수 있는 점이 더 많다고 생각합니다.'는 저자분의 생각에 깊이 공감합니다.

아주 약간의 수정사항을 남겨드립니다.
1. Idea 부분 오타가 있습니다. (간다합니다 -> 간단합니다.)

**Comment by yoonjii** [comment]
친절한 설명 감사드립니다.
해당 분야에 대해 잘 모르고 있음에도 페이퍼 리뷰만 읽고도 바로 이해될 정도로 잘 정리되어 있는 것 같습니다.
각 notation에 대해 자세하게 설명되어 있어서 특히 도움이 되었습니다.

- Typos
0. Introduction (검출된 객체의 > 검출된 객체를)
2. Motivatoin (두 task를 모두를 > 두 task 모두를)
- Additional references
Opinions or questions about the article
Contents wanted to be added or removed
Correcting wrong information
Correcting omitted parts of the template (e.g., reference, author information, ...)

**Comment by yoonjii** [comment]
친절한 설명 감사드립니다.
해당 분야에 대해 잘 모르고 있음에도 페이퍼 리뷰만 읽고도 바로 이해될 정도로 잘 정리되어 있는 것 같습니다.
특히 각 notation과 평가 지표에 대해 자세하게 설명되어 있어서 이해할 때 많은 도움이 되었습니다.

- Typos
0. Introduction (검출된 객체의 > 검출된 객체를)
2. Motivatoin (두 task를 모두를 > 두 task 모두를)
- Opinions or questions about the article
3. Method에서
'이는 학습 단계에서는 이전 프레임의 검출 결과 입력으로 사용할 때 ground truth를 사용하였기 때문입니다.' 부분에 대한 추가 설명이 필요할 듯 합니다.

**Comment by junhahyung** [comment]
안녕하세요, AI 대학원 20218240 형준하입니다.
저는 영어 버전 기준으로 리뷰드립니다.

일단 너무 깔끔하게 잘 쓰셔서 공부에 도움이 많이 된 것 같습니다:)

1> 제가 이해를 못한 것 같은데, confidence 를 구할때 y hat 과 p hat을 곱하는데, p hat은 R^2 의 크기를 가지고 있는데 둘이 어떻게 곱한다는건지 이해가 가지 않습니다.

2> Class-agnostic single-channel heatmap에 대한 설명도 조금 더 있었으면 좋겠습니다.

좋은 리뷰 감사합니다 :)
