### ISSUE TITLE
[2021 fall] SIGGRAPH 2021 AMP: Adversarial Motion Priors for Stylized Physics-Based Character Control (20213349)

### ISSUE THREAD

**Issue by niceDuckgu** [awesome-davian/awesome-reviews-kaist#153]

**Comment by jhjun724** [comment]
안녕하세요. 조천식 녹색교통대학원 석사과정 정현준입니다.
좋은 논문리뷰 감사합니다.

Generative adversarial learning이 로봇의 모션을 위한 강화학습에 어떻게 쓰이는지 배울 수 있었습니다.

추후 수정될 리뷰에서 이러한 부분이 보완되면 좋겠습니다.
1. action과 state transition의 차이점이 명확히 와닿지 않아서 추가로 설명해주시면 좋을 것 같습니다.

2. 리뷰의 설명들이 수식들로 이루어진만큼, 수식에 대한 notation들을 명시해주면 더 편하게 이해가 될 것 같습니다. 예를 들어 style reward의 식과 eq8에서 gradient penalty를 제외한 discriminator observation의 식은 굉장히 비슷해보입니다. $$\Phi$$를 통해 두 식이 의미하는 바는 달라지는데 이의 경우 $$\Phi$$가 어떤 notation을 가지길래 두 식이 의미하는 바가 달라지는지 등의 설명 혹은 정확한 notation이 필요할 것 같습니다.

3. 수식들은 논문에서 캡처하여 업로드 된 것 같은데 폰트 사이즈, 해상도 등이 너무 다양하여 이 부분에 대해서 수정해주시면 좋을 것 같습니다.

감사합니다.

**Comment by hsl323** [comment]
안녕하세요,
NAVER 재직중인 이현수 입니다.
리뷰와 related works들의 링크들이 잘 되있는 것 같습니다. 감사합니다.

몇 가지 코맨트를 남깁니다.
- 리뷰에 수식들이 많은데 수식에 대한 notation이 없어 조금 혼란스러운 것 같습니다. Discriminator의 수식에서 다음의 내용이 수식에 어디에 해당하는지 궁금합니다.
    ```
    Global coordinate에서 캐릭터의 원점(pelvis)의 선속도 및 회전속도
    각 joint의 local rotation / velocity
    각 end-effector의 local coordinate
    ```
  또한 그림에서 수식에 등장하는 r에 관한 내용은 잘 설명이 되어있으나 s, g, a가 무엇인지 설명이 없어 이해하기 어려운 것 같습니다.

Experiment와 result부분에는 동영상 첨부와 함께 잘 설명되어 있어 이해하기 쉽고 재미있게 읽을 수 있었던 것 같습니다.
감사합니다

**Comment by onejoon** [comment]
안녕하세요, 저는 AI대학원 박사과정 장원준입니다.
주제가 흥미로웠고, related work를 통해 motion control을 학습하기 위해 어떤 연구적 흐름이 있었는지 이해하기 좋았습니다. 그러나 method 파트에서 수식이나 알고리즘에 대한 디테일이 부족한 점이 아쉬웠습니다. 디테일 코멘트는 다음과 같습니다.

1. 문제정의가 조금 더 formal하게 제시되면 좋을 것 같습니다.
2. 수식에 대한 notation table이 필요합니다. 또한 몇몇 수식 표현들이 rendering이 안되어 있고, 수식 이미지들의 크기가 일관적이지 않습니다.
3. motion prior로부터 style이 어떻게 선택되는지 간단한 설명이 추가되면 좋을 것 같습니다.
4. Gradient penalty 부분에서 nonzero gradient에 패널티를 주는 것이 instability와 어떻게 연결되는 것인지 궁금합니다.
