### ISSUE TITLE
[2021 fall] ECCV 2018 Image Super-Resolution Using Very Deep Residual Channel Attention Networks (20215618)

### ISSUE THREAD

**Issue by niceDuckgu** [awesome-davian/awesome-reviews-kaist#155]

**Comment by jangting** [comment]
20213789 / 장태영

1. 기존 방법과 한계, 발전방향으로 이어지는 구성이 모르는 분야이더라도 이해하는데 크게 도움이 되었습니다.
2. 최근 NTIRE 같은 super resolution challenge에서는 LPIPS를 사용해서 성능을 평가하던데, 이 논문에서는 이 기술이 부자연스러움이 있어 PNNR과 SSIM만 표현한 것 같습니다.
3. Gating 관련해서 부연 설명을 더 해주시면 좋을 것 같습니다
4. 페이퍼에 있는 결과 이미지(Fig.7)를 보면 선형 정보를 잘 유지하던데, 이것은 attention을 이용해서 생기는 장점이라고 볼 수 있을까요?

**Comment by brightjade** [comment]
안녕하세요, 리뷰 잘 읽었습니다.

### Related work
- 언급된 previous work 논문들도 reference에 citation 해주시면 좋을 것 같습니다.

### Result
- 섹션 제목에 work in progress 는 아직 완성됐다는 것이 아닌가요?
- model size analyses 에서 피겨가 영어 버전에서는 잘 디스플레이가 되는데, 한국어 버전은 조금 이상하게 표기가 됩니다.

**Comment by gyuhyeonsim** [comment]
안녕하세요 도메인 지식이 없음에도 불구하고 리뷰 재미있게 읽었습니다!
몇가지 추가되면 더 읽기 편한 글이 될것 같아 코멘트 남깁니다.

1. 문제 정의에서 수식에 대한 설명이 추가되면 좋을것 같습니다.
2. gating을 설명하는 부분에서 구체적인 설명이 필요합니다 (채널간 비선형성이 무엇인가요?).
3. 리뷰가 짧은데 반해, 줄여진 말들이 (LSC, SSC 등) 너무 많아서 Result 부분에서 줄여진 말들의 의미를 찾느라 시간이 쓰이는 것 같습니다. 그냥 말들을 풀어쓰는게 어떨까요?
4. Evaluation metric에서 YCbCr color space의 Y 채널 이라는게 어떤 의미인지 잘 모르겠습니다 ㅠㅠ.. 좀더 구체적인 설명이 필요할 것 같습니다.

**Comment by Seung-HO-HAN** [comment]
> 20213789 / 장태영
> 
> 1. 기존 방법과 한계, 발전방향으로 이어지는 구성이 모르는 분야이더라도 이해하는데 크게 도움이 되었습니다.
> **Ans) 감사합니다.**
> 2. Gating 관련해서 부연 설명을 더 해주시면 좋을 것 같습니다
> **Ans) [Note ii]에 gating 관련 내용을 추가하였습니다.**
> 3. 페이퍼에 있는 결과 이미지(Fig.7)를 보면 선형 정보를 잘 유지하던데, 이것은 attention을 이용해서 생기는 장점이라고 볼 수 있을까요?
> **Ans) 네 그렇습니다.**
> 4. Result에 Model size analyses 의 이미지가 너무 작습니다.
> **Ans) 수정하였습니다.**
> 5. Eng 버전의 Related work에 한글이 있습니다.
> **Ans) 수정하였습니다.**

> ----------------
> 안녕하세요, 리뷰 잘 읽었습니다.
> **Ans) 감사합니다.**
> ### Related work
> * 언급된 previous work 논문들도 reference에 citation 해주시면 좋을 것 같습니다.
> **Ans) 추가하였습니다.**
>
> ### Result
> * 섹션 제목에 work in progress 는 아직 완성됐다는 것이 아닌가요?
> **Ans) work in progress 삭제하였습니다.**
> * model size analyses 에서 피겨가 영어 버전에서는 잘 디스플레이가 되는데, 한국어 버전은 조금 이상하게 표기가 됩니다.
> **Ans) 수정하였습니다.**

> ----------------
> 안녕하세요 도메인 지식이 없음에도 불구하고 리뷰 재미있게 읽었습니다! 몇가지 추가되면 더 읽기 편한 글이 될것 같아 코멘트 남깁니다.
> **Ans) 감사합니다.**
> 1. 문제 정의에서 수식에 대한 설명이 추가되면 좋을것 같습니다.
> **Ans) 추가하였습니다.**
> 2. gating을 설명하는 부분에서 구체적인 설명이 필요합니다 (채널간 비선형성이 무엇인가요?).
> **Ans) [Note ii]에 gating에 관한 내용을 추가하였습니다.**
> 3. 리뷰가 짧은데 반해, 줄여진 말들이 (LSC, SSC 등) 너무 많아서 Result 부분에서 줄여진 말들의 의미를 찾느라 시간이 쓰이는 것 같습니다. 그냥 말들을 풀어쓰는게 어떨까요?
> **Ans) 내용 보충하였습니다.**
> 4. Evaluation metric에서 YCbCr color space의 Y 채널 이라는게 어떤 의미인지 잘 모르겠습니다 ㅠㅠ.. 좀더 구체적인 설명이 필요할 것 같습니다.
> **Ans) [Note iii]에 YCbCr 내용 추가하였습니다.**
