### ISSUE TITLE
[2021 fall] CVPR 2019 Second-order Attention Network (20213361)

### ISSUE THREAD

**Issue by niceDuckgu** [awesome-davian/awesome-reviews-kaist#156]

**Comment by junwoopark92** [comment]
1. 리뷰한 논문에서 제시한 컴포넌트가 너무 많고 이를 표현한 논문의 그림이 가독성이 좋지않아 간단하게 flow를 정리하는게 더 이해에 도움이 될듯합니다.

2. attention을 생각하면 보통 query, key, value를 생각하여 이해를 하는게 일반적인데 여기서 말하는 attention이 다른개념 아니라면 이러한 방향으로 설명해주면 더쉽게 이해 할수 있지 않을가 싶습니다.

3. second order가 어떻게 구해지고 적용되는지,  그리고 SR에서 second order로 attention을 해야하는 하이레벨한 설명이 있으면 좋을것 같습니다.

**Comment by hsrhee** [comment]
안녕하세요, 논문 요약 감사합니다.

**Method**

* 각 module에 대한 설명이 유기적으로 연결되면 모델을 이해하기에 더 수월할 것 같습니다
* 수식 부분을 이미지 캡처보다 문법에 맞게 입력해주시면 가독성이 더 좋아질 것 같습니다
