### ISSUE TITLE
[2021 fall] ICLR 2020 Picking Winning Tickets Before Training by Preserving Gradient Flow (20217052)

### ISSUE THREAD

**Issue by niceDuckgu** [awesome-davian/awesome-reviews-kaist#157]

**Comment by Seung-HO-HAN** [comment]
안녕하세요, 김경수 교수님 연구실 박사과정 한승호(20215618)입니다.
업로드해주신 awesome review 잘 읽어보았습니다.

Gradient 기반 pruning에 대해 흥미롭게 읽어보았습니다.

**[Peer review]**
1. Figure가 보이질 않습니다. Awesome review guideline에 제시된 파일 디렉토리 구조를 참고해주세요.
2. Problem definition에서 GraSP를 대표하는 수식을 언급해주면 좋을 것 같습니다.
3. equation은 $ $이 아닌 $$ $$ 으로 감싸주세요

감사합니다.
한승호 드림

**Comment by ohmywow22** [comment]
안녕하십니까, 수강생 안성빈입니다.
모델 최적화와 관련하여 최신 기법 소개해주셔서 감사합니다.

1. 최적화 전후의 모델에 대한 비교가 궁금합니다. 해당 알고리즘으로 최적화했을 시 cost나 전후의 parameter 갯수, 정확도 변화 등에 대한 정보가 있으면 정말 좋을 듯 합니다.
2. 사실, 전반적인 아이디어는 전달받을 수 있었지만 이미지와 수식들이 gitbook에 제대로 업로드되지 않아 정확한 이해가 어려웠습니다. 확인하시고 수정해주시면 정말 감사하겠습니다.

감사합니다.

**Comment by ju0209** [comment]
안녕하세요, 좋은 설명 감사드립니다!

1. 그림들이 보이지 않습니다.
2. related work를 통해 기존 기법들과 본 논문과의 차이점 및 흐름을 잘 이해할 수 있었습니다.
3. 수식을 나타내는 그림들이 보이지 않아서 그런지, method 부분의 설명만으로는 정확한 방법을 이해하지는 못했습니다.
   * delta는 weight 값의 변화가 맞나요?
   * '해당 수식을 pruning task에 맞게 ~ term은 사라지게 됩니다.' 부분에 대한 더 자세한 설명이 있으면 좋을 것 같습니다.

감사합니다.
