### ISSUE TITLE
[2021 fall] ICLR 2021 Contrastive syn-to-real generalization  (20208207)

### ISSUE THREAD

**Issue by niceDuckgu** [awesome-davian/awesome-reviews-kaist#158]

**Comment by sanmin0312** [comment]
안녕하세요. 카이스트 녹색교통대학원 김산민입니다.
작성해주신 리뷰 잘 읽었습니다.

전체적으로 잘 작성되었고, 디테일한 내용들까지 잘 설명해주셔서 많은 도움이 되었습니다.
몇가지 코멘트들을 아래 적어놓았으니 수정하실 때 참고해주시면 감사하겠습니다.

### comments

1. Problem definition

- 수식 자체가 이해가 안가는 것은 아니지만 objective function안에 S_train은 사용되지 않고 있으며, 해당 objective function은 어떻게보면 deep learning에서 가장 일반적으로 쓰이는 표현이기 때문에 해당 task를 잘 설명해주지 못하는 것 같습니다.
Domain generalization 설명의 첫번째 수식에서 S^i에서 j,n은 무엇이고, j는 왜 1인지 설명이 없습니다.
- Domain adaptation과는 어떤점에서 다른 task인지 궁금합니다.
- 같은 수식, 같은 설명이 반복되는 경향이 있습니다.

3. Method

- 수식(3)에서 사용한 tau는 image augmentation을 뜻하는 tau와 같은 tau인가요? 같은 tau라면 어떻게 divide로 표현되는지 잘 모르겠습니다.


### typos

- 도멘 -> 도메인
- 10,00 -> 1,000? 10,000?
- 마지막 딴에 -> 마지막 단에
- notions -> notations?
- arameter -> parameter

**Comment by 2na-97** [comment]
안녕하세요,  
너무 정리를 잘 해주셔서 새로운 분야에 대한 이해를 높일 수 있었습니다.  
대체로 잘 정리되어 있어 간단한 코멘트만 남기도록 하겠습니다.  

- problem definition의 zero-shot learning 부분에서 validation을 사용하지 않고 바로 test를 진행했다고 하는데, 이 경우 어떤 장점이 있는지 궁금합니다.
- zero-shot learning에 대한 설명이 조금 더 부가적으로 있었으면 좋을 것 같습니다.

자잘한 typo 외에는 너무 자세하게 설명해 주셔서 더 고칠 것은 없을 것 같습니다.  
감사합니다 :)

**Comment by hannabros** [comment]
안녕하세요, 선한결이라고 합니다.
논문 리뷰 뿐만 아니라 related work에 대한 추가 조사, 논문 이해를 위한 개인적인 견해까지 포함하여 정말 고생하셨다는 것을 한눈에 알 수 있었습니다. 아래 제 커멘트 드리니 참고바랍니다.

## Syn2Real [KOR]
1. Problem Definition
- 만약 우리가 M 개의 학습(soruce) 도멘이 주어졌다면, 학습데이터를 아래와 같이 정의할 수 있습니다. -> 도멘 오타
- Matlab 수식 렌더링이 안된 경우가 있습니다.
- 제 개인적인 궁금증인데, Function H와 관련된 수식 표현이 없고 아래 수식은 오히려 Function E & L에 대한 표현입니다. 이 부분 확인 부탁드립니다.
- 위에 있는 데이터셋을 예시로 들자면, 스케치, 만화, 그림 이미지 만으로 학습한 모델은 real iamge에 테스트 했을 때의 로스를 최소화 하는 것을 학습하게 되는 것이지요. -> image 오타, 앞에서 loss라고 했으므로 한글로 로스가 아닌 영어로 표기를 맞추는 것이 좋아보입니다.
- 사실, ICLR open review에서 한 리뷰어는 syn2real로 제한한 셋팅이 본 논문의 중요도를 제한할 수 있다고 말하기도 했습니다. -> 번역에 대한 이슈일 수도 있는데 중요도를 제한한다는 것이 syn2real에만 한정했다는 것이 아쉬웠다는 의미인가요?
3. Method
- 예를 들어, W_0가 initial state 이고 W_k는 k-th batch dataset에서 학습된 arameter 라고 합시다. -> parameter 오타
**Overall**
- 논문을 설명하기 전에 synthetic data와 domain generalization, zero-shot에 대한 설명을 추가하신 점은 매우 좋은 선택이었습니다.
- 로스, 도메인, 태스크과 같이 용어를 한국어 혹은 영어로 통일하면 좋을 것 같습니다.
- Related Work와 관련하여 논문에서 명시된 내용뿐만 아니라 별도의 내용을 추가하여 컨텐츠를 더 풍부하게 하였습니다.
- Method에 개인적으로 해석한 내용이 인상깊었고 논문 이해에 도움을 주었습니다.
- Matlab 수식 렌데링이 제대로 되지 않은 경우가 있습니다.
## Syn2Real [Eng]
2. Motivation
- Note this related work is seperated in two categories: *first for task, second for learning framework*. -> first for domain generalization task
