### ISSUE TITLE
[2021 fall] CVPR 2020 Real-World Super-Resolution via Kernel Estimation and Noise Injection (20213789)

### ISSUE THREAD

**Issue by niceDuckgu** [awesome-davian/awesome-reviews-kaist#160]

**Comment by junwoopark92** [comment]
1. 기존 방법과 한계, 발전방향으로 이어지는 단락안의 문장 구성이 모르는 분야이더라도 이해하는데 크게 도움이 되었습니다.

2. 3.1.1 kernel estimation 에서  KernelGAN을 이용할때 degradation 이미지와 real에서 patch사이즈로 줄어든 이미지가 fake 와  real의 역활을 하는게 맞는지 아니라면 조금 더 설명이 있으면 좋을듯 합니다.

3. noise가 있는 HR을  Bicubic으로 LR을 만들때 LR에는 noise가 왜 없어지는지 궁금합니다. 그리고, noise가 논문에서 어떻게 정의가 되는걸까요?  보통 noise를 가우시안 noise등을 가정하는데 실제 이미지에서 noise의 유무를 어떻게 판단하는지 궁금합니다.

**Comment by jangting** [comment]
> 20208061 / 박준우
> 
> 1. 기존 방법과 한계, 발전방향으로 이어지는 단락안의 문장 구성이 모르는 분야이더라도 이해하는데 크게 도움이 되었습니다.

감사합니다. 이해가 잘 되셨다니 다행입니다. 👍 

> 2. 3.1.1 kernel estimation 에서  KernelGAN을 이용할때 degradation 이미지와 real에서 patch사이즈로 줄어든 이미지가 fake 와  real의 역활을 하는게 맞는지 아니라면 조금 더 설명이 있으면 좋을듯 합니다.

kernelGAN의 작동 방식을 제대로 이해하신게 맞습니다.
원본 이미지를 crop해서 real로 사용하고,
원본 이미지를 임의 kernel로 downscale한 뒤에 crop한 이미지를 fake로 사용해
discriminator에 input으로 사용하게 됩니다. iteration을 돌면서 임의 kernel을 개선해나가는 것이죠.

> 3. noise가 있는 HR을  Bicubic으로 LR을 만들때 LR에는 noise가 왜 없어지는지 궁금합니다. 그리고, noise가 논문에서 어떻게 정의가 되는걸까요?  보통 noise를 가우시안 noise등을 가정하는데 실제 이미지에서 noise의 유무를 어떻게 판단하는지 궁금합니다.

bicubic kernel의 모양을 보면 센터 픽셀을 최대값으로 두고, 끝으로 갈수록 조금씩 줄어들게 되어 있습니다.
이런 모양의 kernel들은 주변 값을 스무딩시키는 효과가 있어서 이는 결국 noise를 제거하는게 됩니다.

noise는 원본 이미지를 256x256 크기의 patch로 자른 뒤에, 이 patch의 분산이 특정 값(저자가 정한 값) 이내인 경우에 noise patch로 선정하게 됩니다. 분산이 작다는 것은 patch의 pixel 값이 비슷하다는 것을 의미하고, 
이렇게 모인 noise patch들을 LR image 생성에 사용(injection)하기 위해 아래 작업도 하게 됩니다.
1. noise patch를 랜덤하게 고르고
2. noise patch에서 일부분을 32x32 크기로 crop한 뒤에
3. cropped patch의 평균을 cropped patch에 빼준 뒤에
3. 0~255 boundary로 잘라주고
4. 이렇게 생성된 최종 noise patch를 image downscale 후에 전체 이미지에 추가하는 것입니다.

**Comment by junhahyung** [comment]
안녕하세요, AI대학원 20218240  형준하입니다.
SR에 대해서 잘 모르는데도 불구하고 글이 깔끔하게 잘 쓰여있어 공부하는데 도움이 되었습니다 :)

제가 이해를 못한 부분을 위주로 질문 및 코멘트 드리겠습니다.

1. > 왜 k의 합이 1이 되어야 하는지에 대한 설명이 있으면 좋을 것 같습니다
2. > 3.1.4. Degradataion with Noise Injection 이 단원 설명이 조금 더 있으면 좋을 것 같습니다. ID가 무엇인지에 대한 설명도 추가해주시면 좋을 것 같습니다.

감사합니다 :)
2.

**Comment by anneshj** [comment]
안녕하세요, 최현진입니다.
그림 임베딩, 수식 오류가 없고 오타도 없이 내용 정리가 깔끔하게 잘 되어 있습니다.
몇 가지 질문과 마이너한 수정 코멘트 드립니다!
- bicubic kernel은 무엇인가요?
- 각 Loss Function에 대한 설명이 조금 추가되면 좋을 것 같습니다.
- 오타: "noiise"
- 레퍼런스로 적혀있는 숫자가 링크가 되면 더 좋겠네요

잘 읽었습니다:)

**Comment by jangting** [comment]
> 안녕하세요, AI대학원 20218240 형준하입니다. SR에 대해서 잘 모르는데도 불구하고 글이 깔끔하게 잘 쓰여있어 공부하는데 도움이 되었습니다 :)
잘 이해되셨다니 감사합니다 👍 
> 
> 제가 이해를 못한 부분을 위주로 질문 및 코멘트 드리겠습니다.
> 
> 1. 왜 k의 합이 1이 되어야 하는지에 대한 설명이 있으면 좋을 것 같습니다
Kernel(K) shape이 3x3인 경우를 생각해보면, 원본 이미지의 3x3 크기만큼 kernel을 적용해 degradation을 적용하게 됩니다.
k의 합이 1이라 함은 3x3 총 9칸의 합이 1임을 의미합니다.
1이 아닌 경우에는 기존 이미지와 degradation 이미지의 색 분포가 달라지게 됩니다.
색 분포를 일치시키기 위해 kernel의 합이 1에 수렴하도록 하는 것입니다

> 2. 3.1.4. Degradataion with Noise Injection 이 단원 설명이 조금 더 있으면 좋을 것 같습니다. ID가 무엇인지에 대한 설명도 추가해주시면 좋을 것 같습니다.
해당 부분에 대한 설명이 부족했는데, 추가하도록 하겠습니다. ID라 함은 degradation된 이미지를 의미합니다.
> 
> 감사합니다 :)
감사합니다 👍

**Comment by jangting** [comment]
> 안녕하세요, 최현진입니다. 그림 임베딩, 수식 오류가 없고 오타도 없이 내용 정리가 깔끔하게 잘 되어 있습니다. 몇 가지 질문과 마이너한 수정 코멘트 드립니다!
잘 이해되셨다니 감사합니다 👍 
> 
> * bicubic kernel은 무엇인가요?
kernel의 중심이 가장 높은 값을 갖고, 주변으로 퍼질수록 점차 낮아지는 산 같은 kernel이라고 생각하시면 됩니다.
아래 그림을 참고하시면 되겠습니다. paper에 추가하겠습니다.
https://www.wisdom.weizmann.ac.il/~vision/kernelgan/resources/input_images/bicubic_estimations.jpg
> * 각 Loss Function에 대한 설명이 조금 추가되면 좋을 것 같습니다.
설명이 부족했네요. 블로그에 설명 추가하겠습니다.
> * 오타: "noiise"
감사합니다!
> * 레퍼런스로 적혀있는 숫자가 링크가 되면 더 좋겠네요
링크 방법을 찾아서 적용시켜보겠습니다.
> 
> 잘 읽었습니다:)
