### ISSUE TITLE
[2021 fall] ICCV 2021 Finding Representative Interpretations on Convolutional Neural Networks (20215584)

### ISSUE THREAD

**Issue by niceDuckgu** [awesome-davian/awesome-reviews-kaist#162]

**Comment by tungnt101294** [comment]
1. Summary
   
    The article reviews the paper titled ***Finding Representative Interpretations on Convolutional Neural Networks*** by Lam *et al.* It focuses on representative interpretation for similar images via an unsupervised approach.

2. Detailed Reviews

    Strengths:

     * In general, the author of the article (from this point on, referred to as simply *the author*, and not to be confused with the authors of the original paper) seems to have done a decent job of capturing the essence of the paper.
     * The problem definition is well formulated. Core concepts and mathematical notions are given.
     * Important implementation details and results are well summarized.

    Reviewer's Suggestions:

     * There is a need for a slow, friendly introduction. For example, the author can provide more information on why we need interpretability in deep learning.
     * Some important concepts such as co-clustering or semantic distance need much more explanation.
     * The portions involving mathematic notions and formulas also need more explanation.
     * Frankly speaking, the author seems to understand the paper very well, to provide such a concise article. However, I believe it is more of a ***summary*** of the paper than it is a review. The author provides all the core details from the paper but it would be much better if they could give their own opinions on, for example, the importance of interpretability. 
     * Or they could offer some thoughts on why the design choices were made by the authors of the papers, which would give the readers more information they cannot get from the paper itself.

**Comment by earlgrey97** [comment]
안녕하세요. 전자과 석사과정에 재학중인 박나현입니다.
전반적으로, 깔끔하게 리뷰를 적으신 것 같아, 잘 읽었습니다. problem definition도 깔끔하게 한 눈에 보이게 잘 해주신 것 같고, notation이나 method부분도 전체적으로 간단하게 잘 적으신 것 같아요.

몇 가지 사소한 부분에 대해 comment 남깁니다...!
1)  한국어 버전과 영어 버전 모두에서 representative interpretation(파트제목부분 큰 글씨)을 'representaitive'로 오타를 내신 것 같은데 확인 후 수정하시면 좋을 것 같습니다.
2) scsc problem에 대해 제일 먼저 언급된 부분이 motivation의 idea인 것 같은데, scsc의 설명은 method부분에 나오는 것 같습니다. 읽는 사람 입장에서는 idea에서 처음 scsc problem이 언급되었을 때 해당 부분에 대한 설명이 없어서 이해가 힘들 것 같습니다. 따라서, 그 부분에서 나중에 설명이 나온다는 언급이라도 한번 해주면 조금 더 친절한 paper review가 될 것 같습니다.

감사합니다.

**Comment by Errors-Everywhere** [comment]
Hi, I'm Ahmed Magd (20214239).

The review is concise and well written. However, I suggest the following:

- Giving illustrative examples to the methods proposed, to show why they should give a good result. (For example, try to mention why the procedure of “Ranking similar images” using the proposed distance metric, should give a good result.)
- There are very few number of typos and grammatical mistakes in the article (as in: “… follow the same heat mapto generate the …”, “This experiment evaluate …”). Consider fixing them in the final draft.
- Using bullet points is great! But using them excessively in the article (in my opinion) may not be the best thing for the reader.
- Overall, I think this is a good review, but it needs more illustrative examples and not just a summary of the important points in the paper.
