### ISSUE TITLE
[2021 fall] ECCV 2020 Contrastive Learning for Unpaired Image-to-Image Translation (20214396)

### ISSUE THREAD

**Issue by niceDuckgu** [awesome-davian/awesome-reviews-kaist#163]

**Comment by amy-hyunji** [comment]
안녕하세요, 논문 요약 감사합니다. 몇 가지 제안 및 오타 부분 공유드립니다.

1. `Method - Multilayer, patchwise contrastive learning`에서 아예 다른 이미지에서 negative sample을 가져왔을 때 실험의 성능보다 이미지 내에서 샘플링 했을 때가 더 좋은 결과가 나왔다는 부분에 대한 성능 비교 그래프나 표가 있다면 첨부해주시면 더 좋을 것 같습니다!
2. light한 모델인 Fast CUT은 CUT와 어떻게 다른지에 대한 부분이 없는 것 같습니다.

감사합니다 :)

**Comment by bulsajyo** [comment]
안녕하세요 기계공학과 박사과정 오상윤(20215201) 입니다.
먼저 리뷰글 잘 읽었습니다. 전체적으로 설명이 잘 되어 있었는데요, 특히 related work에서 다른 연구들의 설명과 한계점을 자세히 명시한 점이 좋았습니다.
아래에 코멘트 남겨드립니다.
1. Motivation에 있는 image translation에 대한 설명처럼 Problem definition에서 task에 대한 설명을 풀어서 설명하면 더 좋을 것 같습니다.

2. 이미지들의 캡션 넘버링과 관련 설명을 달면 더 좋을 것 같습니다.

3. Result의 이미지에서 SOTA에 비해 CUT 모델이 어떻게 향상되었는지 몇 예시에 대해 확대 사진이 있으면 좋을 것 같습니다.
