### ISSUE TITLE
[2021 fall] CVPR 2021 FSCE: Few-Shot Object Detection via Contrastive Proposal Encoding (20213239)

### ISSUE THREAD

**Issue by niceDuckgu** [awesome-davian/awesome-reviews-kaist#164]

**Comment by shjung13** [comment]
안녕하세요,
모티베이션에 대한 설명과 기존 방법론에 대한 문제 + 해결방법 매칭이 아주 잘 되어있어서 어렵지 않게 따라갈 수 있었습니다.

몇 개 없지만 제 리뷰는 아래와 같습니다.

4. Method
- CPE Loss I{.}는 indicator function인가요?
- CPE Loss I_{k !=i} 는 I{k != i}로 수정해야할 듯 합니다.
- Proposal consistency control에서 g(u_i) 정의를 추가해야할 듯 합니다.

5. Experiment & Result
- 리뷰의 처음에 few shot learning에서의 n, k에 따른 challenging한 정도에 대해 설명을 해주셨는데 실험 결과에서는 K를 바꾼 결과는 보였지만 n에 다른 성능 변화는 보이지 않은 듯 한데요, 혹시 관련된 결과도 있을까요?

추가사항
오타:  RoI feature extractor가 unfeeze되면 성능이 저하되지만 --> unfreeze

고생하셨습니다, 감사합니다.

**Comment by rlqja1107** [comment]
안녕하세요, 리뷰를 보면서 개인적인 생각을 정리하겠습니다.  
1. Method 설명하기 이전에 Related Work와 다른 관련된 설명을 통해 이후의 내용을 쉽게 이해할 수 있었습니다.  
2.  Supervised Contrastive Learning이 Few-Shot Object Detection에 도움이 되는 이유가 Few-shot의 Object Class의 Feature가 Base Class의 Feature와 유사(?)하다면 Contrastive Learning을 통해 Few-Shot의 Class가 비슷한 Base Class 또는 Few-shot Class로 분류되어 이전보다 더 잘 맞춘다고 이해가 되는데 맞는가요? 왜냐하면 결국은 Contrastive Feature를 이용해서 Contrastive Learning을 하기 때문이라고 생각이 듭니다. 제가 생각한 직관이 맞다면 이를 Review에 적어주시면 직관적으로 이해하기가 편할 것이라고 생각합니다.  
3.  글 흐름대로 읽었을 때 이해가 잘 됩니다. 핵심부분만 순서대로 나열한 것이 이해하는데 큰 도움이 되었습니다.  


감사합니다.

**Comment by heyzude** [comment]
안녕하세요, 좋은 리뷰 감사합니다.
정리가 되게 잘 되어있어서, 사소한 부분들만 알려드리려고 합니다.

1. problem definition에서: 예를 들어 의 경우는 2개의 class
2. 수식 중 $이 하나만 있어서 제대로 표현이 못 된 부분들이 있습니다.

감사합니다.
