### ISSUE TITLE
[2021 fall] ICCV 2019 FDA: Feature Disruptive Attack (20213132)

### ISSUE THREAD

**Issue by niceDuckgu** [awesome-davian/awesome-reviews-kaist#165]

**Comment by johnlee92** [comment]
안녕하세요. NAVER 재직중인 이재현입니다.
리뷰를 잘 작성해주셔서 재밌게 읽었습니다. 몇 가지 코멘트 남깁니다.

1.  적대적 공격 및 적대적 예제에 대한 설명은 충분하였으나, 적대적 공격이 왜 필요한 지 설명이 추가되면 좋을 것 같다는 생각이 들었습니다.
2. 중간에 삽입된 이미지의 크기가 다소 작아 가독성이 조금 떨어져 보입니다.
3. Style Transfer를 이용하여 기존 방법들의 한계를 보인 점이 인상깊었습니다.

감사합니다.

**Comment by hsl323** [comment]
안녕하세요,
NAVER 재직중인 이현수 입니다.
problem definition부터 설명을 잘 써주셔서 이해하기 쉽고 재밌게 읽었습니다.

몇 가지 코멘트를 남깁니다.
- style transfer를 이용하여 기존 방법들의 한계를 보인 figure가 feature level에서 이해하기 쉬워 좋은 것 같습니다. 한가지 궁금한 점이 있다면 혹시 논문에 feature level이외의 image 결과물도 있을까요?? (adversarial attack은 사람이 보기에 차이가 없어 보여야 하는 것으로 알고 있는데 feature level에서 수정을 해도 차이가 없을지 궁금합니다)
- 재현님이 남겨주신 리뷰와 같이 이미지의 가독성이 조금 더 좋아졌으면 좋겠습니다.
- 또한 마찬가지로 적대적 공격이 필요한 이유에 대해 설명해 주시면 좋을 것 같습니다. (적대적 예제를 생성하여 최종적으로 무엇을 하려고 하는 것인지)

전체적으로 설명을 쉽게 잘 해주셔서 좋았습니다.
감사합니다.

**Comment by dkmv0623** [comment]
안녕하세요, 전자과 대학원 석사과정에 재학중인 고강욱입니다.
리뷰 잘 읽었습니다.
몇 가지 코멘트 남깁니다.
1. 다른 분들도 말씀하셨듯이 그림의 크기가 조금 더 크면 좋을 것 같습니다.
2. Problem definition과 related work 부분에도 이해를 도울 수 있는 이미지가 있으면 더 읽기 편할 것 같습니다.
3. 3-2에서 feature의 거리를 증가/감소시킨다고 설명하는데, feature의 거리 라는 용어가 정확히 어떤 의미인지 조금 더 설명해주시면 좋을 것 같습니다.

감사합니다.
