### ISSUE TITLE
[2021 fall] NuerIPS 2017 Neural Discrete Representation Learning (20214591)

### ISSUE THREAD

**Issue by niceDuckgu** [awesome-davian/awesome-reviews-kaist#166]

**Comment by amy-hyunji** [comment]
안녕하세요, 논문 요약 감사합니다. 몇 가지 제안 및 오타 부분 공유드립니다.

1. `problem definition` 첫 번째 문장에서 Gernerative이 Generative로 변경되어야 할 것 같습니다.
2. 평가 방식으로 사용된 `bits/dim`에 대한 설명이 추가되면 좋을 것 같습니다. 또한 결과에 대한 표가 있다면 표로 첨부하여 정리하면 더 보기 좋을 것 같습니다.
3. 기존의 discrete latent VAE와 해당 paper의 method가 어떻게 다른지와 각각의 모델에 대한 설명이 좀 더 적혀 있으면 좋을 것 같습니다.

감사합니다 :)

**Comment by jangting** [comment]
20213789 / 장태영

1. Model Architecture에서 ```(Forward)``` 대신 ```###Forward``` 문법으로 적는게 나을 것 같습니다.
   (아래에 있는 ```(Backward)```도 동일합니다)

감사합니다 👍

**Comment by KanghoonYoon** [comment]
안녕하세요 산업및시스템 공학과 박사과정 윤강훈 (20215550) 입니다. 
1. Intro
  논문의 Motivation 과 기존문제의 한계를 명확히 언급해주셨기 때문에
이해하기가 쉬웠습니다. 다만, 기존에도 discrete representation learning을
진행해왔었는데, 그것보다 성능이 좋다라는 것 이외에도 태클한 문제가
무엇인지 적어주시면 좋을 것 같습니다.

2. Result
  Result 에서 결과를 숫자를 통해서 언급해주셨지만, 논문에 기재된 표라도
넣어주시면 좋을 것 같습니다.
