### ISSUE TITLE
[2021 fall] CVPR 2015 A Convolutional Neural Network Cascade for Face Detection (이재현)

### ISSUE THREAD

**Issue by niceDuckgu** [awesome-davian/awesome-reviews-kaist#168]

**Comment by jangting** [comment]
20213789 / 장태영

1. 기존 방법과 한계, 발전방향으로 이어지는 구성이 모르는 분야이더라도 이해하는데 크게 도움이 되었습니다.

2. Face detection에 cascade 구조로 속도 향상시킬 수 있는 것을 배웠습니다. regression 분야에도 응용하면 속도 개선을 이룰 수 있을 것 같습니다.

3. 첫번째 그림에서 network를 통과한 뒤에 녹색 박스의 크기가 같은데, 12-net 결과는 12x12 크기여야 하지 않을까요?  왜 저렇게 되는지 궁금합니다.
4. 12-net 설명에 '''12x12x3'''이 아니라 ```12x12x3``` 인 것 같습니다.
5. 학습에 사용한 데이터셋에 대한 정보 및 샘플 이미지가 있으면 좋을 것 같습니다.

**Comment by oglee815** [comment]
20213784 / 이현제

상세한 설명이 담긴 리뷰 잘 읽었습니다.

간략한 코멘트를 남기자면,

1. CNN Structure를 설명할 때 전체를 빠르게 개괄 할 수 있는 문장이 있으면 좋을 것 같습니다. 본 논문에서는 아래처럼 되어 있습니다.
There are 6 CNNs in the cascade including 3 CNNs for face vs. non-face binary classification and 3 CNNs for bounding box calibration, which is formulated as multi-class classification of discretized displacement pattern

2. Runtime Efficiency가 논문에서 주장하는 중요한 포인트 같은데 해당 부분에 대한 설명이 좀 더 있으면 좋을 것 같습니다.

좋은 리뷰 감사합니다!

**Comment by KanghoonYoon** [comment]
안녕하세요 산업및시스템공학과 박사과정 윤강훈 (20215550) 입니다.

논문의 모티베이션부터, method 까지 쉽게 이해할 수 있도록 쓰여있는 것 같습니다. 피드백 드릴 사항이 많아 보이지 않습니다.

그나마 권고 드릴 사항은,

논문의 contribution 으로서 1) 정확한 이진분류와 2) 빠른 연산이 가능하게 된 Face Detection 이 제안되었다고 이해하고 있습니다.  이 어느 부분에서 이루어졌는지 Method의 특정파트를 지칭하며 설명을 더해주시면, 리뷰를 읽고 제안된 모델 구조의 의도를 더 쉽게 이해할 수 있을 것 같습니다. 

감사합니다
