### ISSUE TITLE
[2021 fall] CVPR 2014 Rich feature hierarchies for accurate object detection and semantic segmentation (권문범)

### ISSUE THREAD

**Issue by niceDuckgu** [awesome-davian/awesome-reviews-kaist#169]

**Comment by pmh9960** [comment]
1. Problem definition
Object detection이 어떤 테스크인지 전혀 설명하고 있지 않습니다.
2. Motivation
Motivation에 대한 내용이 전혀 없고 메소드에 대한 절차만 설명하고 있습니다.
3. Method
전체 과정이 어떻게 진행되는지 그림으로 나타나 있으면 좋을 것 같습니다.

기타
reference: 원문, selective search 정도는 걸어주셔야 할 것 같습니다.

**Comment by 2na-97** [comment]
Problem Definition
- Object Detection task가 무엇인지에 대한 설명과 다른 task와는 어떤 차이점을 가지고 있는지에 대해서 설명해 주시면 좋을 것 같습니다.

Related Works
- Related Work 부분이 빠져 있어서 이 부분에 selective search, SVM 정도의 내용을 넣어 주시면 이해하는 데에 좋을 것 같습니다.
- 기존의 Object Detection은 어떻게 이루어지고 있었는지 (sliding window..) 등등의 내용을 넣어주시면 RCNN이 이 방법들과 비교해서 어떤 차이점을 보이는지 이해하는 데에 편할 것 같습니다.

Experiment & Results
- 추가가 필요할 것 같습니다.

Conclusion
- RCNN 이후에 다른 Fast, Faster RCNN이 나왔는데, 이런 것들이 나오게 된 RCNN의 한계를 명시해 주시면 좋을 것 같습니다.

Reference
- 추가가 필요할 것 같습니다.

**Comment by shjung13** [comment]
안녕하세요,

아래는 제 리뷰입니다.

1. Problem definition
- 해결하려 하는 task에 대한 설명과 정확한 입 출력에 대한 설명이 필요할 것 같습니다.
2. Motivation
- motivation에 대한 내용 대신 method에 대한 설명이 들어가져 있는 것 같습니다. 
- Related work 또한 추가가 필요할 듯 합니다.
3. Method
- Algorithm1 figure가 작아 잘 안보입니다.
- 해당 알고리즘에 나온 notation들에 대한 정의와 설명이 필요할 듯 합니다.


감사합니다.
