### ISSUE TITLE
[2021 fall] 2021 CVPR Progressively Complementary Network for Fisheye Image Rectification Using Appearance Flow (진영화)

### ISSUE THREAD

**Issue by niceDuckgu** [awesome-davian/awesome-reviews-kaist#170]

**Comment by ohmywow22** [comment]
안녕하세요, 안성빈입니다.
카메라 왜곡에 대한 딥러닝 모델을 통한 보상이라는 흥미로운 주제에 대해 자세히 리뷰해주셔서 잘 이해한 듯 합니다.

1. 논문의 주요 아이디어인 Feature Correction Layer 관하여 정말 자세히 설명해주셨는데, appearance flow map을 활용하는 부분에 대하여 잘 이해되지 않았습니다. 학습 파라미터가 사용되지 않는다는 말씀을 하셨는데, 그렇다면 appearance flow map을 통한 보정이 어떻게 이루어지는지 간단하게 설명해주실 수 있을까요? 두 output간의 곱으로만 표현되는지, 아니면 어떠한 관계식이 들어가는지 궁금합니다.
2. Loss들과 관련하여 (Content loss, Style loss 등) 해석적인 의미에 대한 설명이 조금이라도 있으면 이해에 큰 도움이 될 것 같습니다.
3. 이미지 크기나 수식의 gitbook용 표현 등을 수정해주시면 감사하겠습니다. ($$수식$$)

리뷰를 정말 자세히 해주셔서 크게 어려운 내용이 없었던 것 같습니다.
감사합니다.

**Comment by anneshj** [comment]
안녕하세요. 최현진입니다.
어안 왜곡에 대한 보정 주제는 처음 접해보는데 흥미로운 것 같습니다.
핵심을 쉽게 파악할 수 있고, 논문에 없는 내용도 추가적으로 설명 적어주셔서 좋았습니다.

아래는 몇 가지 궁금한 점과 마이너한 수정 포인트입니다.
- camera calibration 종류가 여러가지가 있을 것 같은데, 카메라의 어떤 부분을 calibration 하는건가요?
- Related work의 DR-GAN 부분에서 보면 "정상 이미지 외에는 추가 label이 필요가 없는 점 또한 장점"이라고 나와 있는데요, 정상 레이블이라는 것이 왜곡사진과 정상사진의 페어를 말하는 것인가요? 그렇다면 그것 자체로 이미 label이 존재하는 것 아닌가요?
- Markdown 표기가 깨어지는 것들이 있습니다. 특히 수식의 경우 가독성이 떨어져서 보정이 필요할 것 같습니다. $를 하나 더 붙이시면 정상적으로 표기됩니다. 레퍼런스 표기도 수정 필요.
- 이미지 크기가 좀 작습니다.
- 오타: "컨이미지", "각가의 출력", "ploynomial"
- Evaluation metric (ex. PSNR, SSIM, FID, CW-SSIM)에 대한 설명이 있으면 좋겠습니다.
- 본문에 보면 "multi-scale loss를 통해, decoder에서 사용되는 각각의 feature map들이 더 잘 학습될 수 있다고 이야기합니다"라고 나와 있는데 저자들이 그렇게 이야기하는 근거가 있나요? 예를 들면 ablation study 같은 거요.

리뷰 잘 읽었습니다.
감사합니다.

**Comment by baeseongsu** [comment]
안녕하세요, 배성수입니다.
재밌는 논문 소개해주셔서 감사합니다.

해당 Paper Review를 읽으며 몇 가지 생각난 피드백을 전달드립니다.
- 앞 부분에서 Problem을 정의하고 Motivation을 통해 Idea를 제안하는 부분까지, 이 연구의 핵심을 파악하는데 도움이 많이 되었습니다.
- 해당 리뷰 글에 등장하는 이미지들의 사이즈가 좀 더 크면 좋을 것 같습니다.
- 중간에 Loss 수식은 잘 표현되어 있는데, 일부 수식 렌더링이 깨져있는 것 같습니다.
- Evaluation metric에 대한 설명이 필요한 것 같습니다.

감사합니다.
