### ISSUE TITLE
[2021 fall] arXiv Swin Transformer: Hierarchical Vision Transformer using Shifted Windows (이현수)

### ISSUE THREAD

**Issue by niceDuckgu** [awesome-davian/awesome-reviews-kaist#171]

**Comment by bo-10000** [comment]
### 오타
- Title: Trensformer -> Transformer
- Related work > self-attention/Transformers to complement CNNs: biasic -> basic
- Related work > Transformer based vision backbones: calssification -> classification
- Idea: hyrachical -> hierarchical
- 3.1. shifted window based self-attention: 첫 번째 문장에서 'window based multi-head self attention (W-MSA)라' 에서 '~고 합니다'가 빠진 것 같습니다.
- 3.1.shifted window based self-attention: 마지막 문단 slef-attention -> self-attention

### 서식 관련
- Figure이 모두 보이지 않습니다
- in-line 수식들이 모두 깨져 있습니다.
- Author 정보가 누락되었습니다.

**Comment by KevinMIN95** [comment]
안녕하세요. 
우선 좋은 리뷰 논문 감사합니다.

1. ViT 가 low-resolution feature map에 의해 general-purpose backbone으로 사용되기 적합하지 않다는 부분이 잘 와닿지 않는것 같습니다. 
2. Figure 들이 보이지 않습니다. 
3. in-line 수식들이 적용이 되지 않은 것 같습니다.

**Comment by csleemooo** [comment]
안녕하세요.

리뷰 잘 읽어보았습니다. 관련해서 제 의견 간단하게 전달해드리겠습니다.

1. Figure와 대부분의 수식이 깨져서 내용을 이해하기가 좀 어렵습니다. 수정 부탁드립니다.
2. Shifted Window based Self-Attention에서 computation complexity에 MSA, W-MSA 모두 hw term이 들어가는 것 같은데, 연산 측면에서 제곱이 빠짐으로 인해 얼마나 실용성이 있어지는지에 대한 설명이 있으면 좋을 것 같습니다.
3. 그림이 없어서 이해하기 힘들수도 있지만, shifted window가 connection에 어떻게 도움이 되는지 글만 보고는 이해하기 어렵습니다.
4. 논문의 저자들이 W-MSA와 SW-MSA를 모두 사용한 것인가요? 왜 둘다 사용한 것인가요?
5. classification task에서는 hierarchical한 구조를 사용하지 않았을까요? 결론을 보면 그런식으로 읽혀지는데, 맞다면 이유가 무엇일까요?

감사합니다.
