### ISSUE TITLE
[2021 fall] CVPR 2021 Pre-Trained Image Processing Transformer (박준형)

### ISSUE THREAD

**Issue by niceDuckgu** [awesome-davian/awesome-reviews-kaist#172]

**Comment by ksalsw1996DM** [comment]
안녕하세요 이승우 입니다.
1. Super-Resolution task에서는 dataset pair를 어떻게 matching시켰나요? x2, x3, x4 SR task가 있다고 되어있는데, downsample->복원인지, 혹은 데이터 자체가 그러한 pair가 있는지 여쭤보고 싶습니다.
2. encoder head / decoder tail이 task마다 구분이 되어있는데, 이는 task에 따라 나머지 3개의 head는 inactivate된다고 이해하면 될까요? 이 부분에 대한 설명이 조금 더 자세하게 된다면 좋을 것 같습니다.
3. 기본적으로 pre-training architecture의 경우, 거대한 scale의 데이터셋에서 내부적으로 학습 하고(MLM/NSP) 그 다음 지정한 task에 대해서 fine-tune하는 모델이라고 이해하고 있습니다. 그런데 해당 논문에서 training과정에서 사용하던 $$L_supervised$$은 어떤 corruption을 주어서 학습하였나요? 이 부분에 대해서 설명이 살짝 추가하면 좋을 것 같습니다.
감사합니다

**Comment by ohmywow22** [comment]
안녕하세요, 안성빈입니다.
좋은 리뷰 감사합니다. 대규모 데이터에서의 선행학습된 모델을 통해, Multi-head 및 Multi-tail 구조로 다양한 품질 향상을 제시하는 내용이 흥미로웠습니다.

1. "Features를 "word"처럼 간주 될 수 있도록 패치로 분할된다"는 내용이 있었는데, "word"처럼 이라는 것이 정확히 어떤 의미인지 잘 모르겠습니다. Attention 모듈을 사용하는 것을 설명하기 위한 비유로 생각하면 될까요?
2. Multi-head와 Multi-tail 구조라면, 여러 개의 인풋 X 훈련된 tail의 갯수만큼 아웃풋을 내놓는다는 뜻으로 이해할 수 있는지 궁금합니다. 그리고 모델 자체가 pre-trained임을 특징으로 하는 듯 한데, 사용하기 위한 추가적인 과정은 필요없는지 궁금합니다.
3. "모델이 pre-training하지 않거나 소량 학습되는 경우 CNN 모델이 더 좋은 성능을 보여주지만, 대규모 데이터에선 transformer 기반 pre-trained 모델(IPT)이 성능을 압도합니다." 라는 구절에서, 앞의 내용은 둘 모두 pretrained weight가 적용되지 않은 초기 상태에서 훈련까지 진행할 경우를 말하는 건가요? 아니면 pretrained 된 모델이라도, 소량의 데이터에서는 fine-tuning을 거치더라도 CNN이 더 좋은 성능을 나타낸다는 뜻인가요?
감사합니다.

**Comment by baeseongsu** [comment]
안녕하세요, 배성수입니다.
좋은 리뷰 논문 감사합니다ㅎㅎ

해당 Paper Review에 대한 Feedback 전달드립니다..
- 이 논문과 관련된 연구들이 많을 것으로 생각되는데, Related Work 부분에서 Bold 표시로 Idea를 제시해주신 부분 덕분에 핵심을 파악하기 좋았습니다.
- 각각의 Downstream Vision Task가 간략하게 설명되어 있어 읽기 편했습니다
- 모델/수식/결과 표에 대한 사이즈가 크면 더 보기 좋을 것 같습니다!
- 이미지 중에서 스크롤된 부분이 캡쳐가 되어 있는 것 같습니다.
- 실제 렌더링 이후의 가독성을 위해, 문장 배치를 고려해보는 것도 좋을 것 같습니다.

감사합니다.
