### ISSUE TITLE
[2021 fall] AAAI 2021 Self-Domain Adaptation for Face Anti-Spoofing (고나은)

### ISSUE THREAD

**Issue by ddehun** [awesome-davian/awesome-reviews-kaist#175]

**Comment by YoonjinXD** [comment]
안녕하세요. 
AI 대학원 석사과정 재학 중인 정윤진 입니다.
작성해주신 논문 요약에 대한 리뷰입니다.

1. The attached figures do not work.
2. The method part's explanation looks weak and short. Could you explain the details?
3. In section 3, It would be better to explain the sentence 'Also, orthogonality is used to prevent the feature mode collapse'. 
4. In the 'Experiment setup' section, the first sentence 'This section should contain:' looks like from the given template.
5. In the 'Result' section, there is a typo. 'Thus, this method outperforms all of the state-of-the-art baseline methods only except RFM, which **tilizes** meta-learning technique as well'

감사합니다.
정윤진 드림

**Comment by HATAEWOOK** [comment]
문화기술대학원 석사과정 하태욱(20214631) 입니다
섹션별로 리뷰 작성했습니다

## 1. Problem definition
- Face anti-spoofing에 대한 definition이 상세하게 되어있으면 좋을 것 같습니다. 예시를 보여줄 이미지가 있으면 도움이 될 것 같습니다.  
## 3. Method
- 이미지가 누락되어 있습니다
- 더 자세한 내용이 필요할 것 같습니다. 정확히 각 step에서 무슨 일이 일어나는지 수학적으로 설명해주셨으면 합니다
## 4. Experiment & Result
### Experimental setup
- 가독성이 많이 떨어집니다. 항목을 나누거나 표를 이용하면 좋을 것 같습니다. 
## 5. Conclusion
- 이 논문의 contribution 혹은 novelty한 포인트가 어떤 것인지 정리되면 좋을 것 같습니다.

**Comment by jyh2378** [comment]
안녕하세요.
작성해주신 글 재밌게 잘 읽었습니다.
다음 부분이 보완되면 더 좋은 글이 될 것 같습니다.
1. 이미지가 누락되어 있습니다.
2. 모델 학습 전략에 대한 부분, loss function의 설계에 대한 설명이 추가되면 더 좋을 것 같습니다.
