### ISSUE TITLE
[2021 fall] CVPR 2017 MobileNets - Efficient Convolutional Neural Networks for Mobile Vision Applications (20214239)

### ISSUE THREAD

**Issue by dudrrm** [awesome-davian/awesome-reviews-kaist#187]
initial commit

**Comment by dudrrm** [comment]
Hi, I'm Soyoung Yang (20208207). Nice to meet you.

*Italic* comes from your origin post, and others are my opinion.



### Rendering Issue

* The images seem to be uploaded into GitHub repo: "assets/PAPER_ID/". You should follow the "How to contribute?" section.
* Also, in the equation, \$y\$ does not render in gitbook, so revise them into \$\$y\$\$. Then, it will be rendered into math equations as we expect.



### Overall review

1. Needs grammar check in detail.
2. Add the "Take-home lesson" section after conclusion one. 
3. How about adding related works studied after the publication of this paper? Or any interesting application examples that utilize MobileNets. I think there would be diverse applications due to its computational efficiency. 



### Detailed feedback

#### Section 1

* *The main problem that this paper tries to solve is the fact that most of the powerful CNNs that were used for computer vision applications are quite large in size.*
  * --> can be rephrased as follows for readability
  * " Most of the powerful CNNs used for computer vision tasks require large memory and are hard to deploy in mobile phones. Then how can we alleviate this problem? In this paper, ~ "
  * I think this paper review post does not have to follow academic writing style, how about making text style more natural way?



#### Section 2

2.1.

* *As these tiny improvements in the accuracy will lead to large and complex models in terms of size and computational cost. **Which** will hinder these models from being deployed in applications that are run on computationally limited platforms.*
  * Why "Which" is the subject? This needs a revision.
* *while doing keeping*
  * means "while keeping"?

2.2. ~ 2.3.

*  *Mult-Add* 
  * --> not "multi-add" ? Is "Mult-add" correct?



#### section 4

* I can not access the notion link, which seems to require access to your personal notion page. How about revising this section to include all results on this single page?

**Comment by hannabros** [comment]
Hi, this is Hangyeol Sun and I enjoyed reading your review.
Below are some of my comments.

4. Experiments & Result
	* Should specify which datasets used and how they evaluated their work.
	* It’s better to write the full result in the gitbook not in your personal notion (The result on both depth wise separable vs full convolution mobile net and mobile net width multiplier and resolution are not shown in your notion due to the authentication issue)
	
**Overall**
	* Related works should be added.
	* Images and math functions are not well rendered.
	* Figure number does not match the image. Probably because the image is not well rendered.
	* Motivation & Method are well described but the experiment and results need more modification.
	* No comment on lessons learned.

**Comment by JunbongJang** [comment]
Hi, Ahmed.
This is Junbong Jang.
These are my comments to improve your article.

- I can spot multiple grammar mistakes. You can try Grammarly to find your grammar mistakes.
- I like the examples you provided for the explanation but they were hard to read since figures and math expressions are not rendered.
- The links to the notion page do not work!
- I felt that your explanations are sometimes unnecessarily long. For instance, your problem definition can be rephrased as follows "Most of the powerful CNNs that were used for computer vision applications are quite large in size and hard to deploy in mobile phones or other lightweight devices. The authors of this paper handle this issue by MobileNet."
