### ISSUE TITLE
[2022 spring] ICCV 2021 Self-Calibrating Neural Radiance Fields (20208200)

### ISSUE THREAD

**Issue by jnypark** [awesome-davian/awesome-reviews-kaist#446]
NeRF는 처음 접해보는데 흥미로운 것 같습니다.
본 논문에 대한 설명이 그림과 함께 제시되어 어렵지 않게 따라갈 수 있었습니다.
아래는 마이너한 수정 포인트입니다.

- Experimental Setup 의 데이터 셋의 scene > scenes
- Improvement over NeRF section에서 렌더링 결과를 시각화 한 부분에 대한 설명이 추가되면 좋을것 같습니다. (예 ) b,c,d의 차이
 
리뷰 잘 읽었습니다.
감사합니다.

**Comment by ddehun** [comment]
@jinyxp 안녕하세요. 이슈 제목의 학번은 리뷰 article의 author학번으로 해주시고, 피어리뷰 내용은 댓글로 남겨주세요! 감사합니다

**Comment by emjay73** [comment]
@jinyxp 안녕하세요 좋은 의견 감사드립니다.
조교님 말씀은 제가 만든 이슈에 댓글로 의견을 남기라는 말씀이신 것 같습니다.
아래는 제가 만든 이슈의 링크입니다.
https://github.com/awesome-davian/awesome-reviews-kaist/issues/353
감사합니다.
