### ISSUE TITLE
[2022 Spring] Pose Recognition with Cascade Transformers (20218254)

### ISSUE THREAD

**Issue by geon0325** [awesome-davian/awesome-reviews-kaist#493]
The review is well-written, providing details of the paper. Some of my comments are:

- The venue of the paper seems to be missing.
- It's good to show the pseudocodes of the method, but I think it would be better you provide some comments on them.
- I think some summary of the paper (e.g., take-home message) can provide better insights for the readers.
- Experimental results are missing.

**Comment by enver1323** [comment]
Dear Geon Lee, thank you so much for your review. If you do not mind, could, you, please, transfer your review to this [issue](https://github.com/awesome-davian/awesome-reviews-kaist/issues/458). As far as I remember, it was instructed to include ID of paper review author and not reviewer. Thank you for your consideration.
