### ISSUE TITLE
[2022 Spring] SegFormer [Kor] (20208200)

### ISSUE THREAD

**Issue by geon0325** [awesome-davian/awesome-reviews-kaist#494]
좋은 review 감사드립니다. 읽기 수월하고 구체적으로 method/experimental results 등을 적어주신 것 같습니다. 실험 결과 이미지 중에서 글씨가 잘 안보이는 것이 있어서 수정해주시면 읽기 더욱 편할 것 같습니다. 또한 evaluation metric이 저에게는 생소한 것 같은데, 관련 설명을 해주시면 좋을 것 같습니다.

**Comment by ddehun** [comment]
@geonlee0325   안녕하세요. 배정받으신 리뷰의 작성자 분의 학번을 이슈 제목에 기입해주시고, 이미 해당 이슈가 있다면 그곳에 댓글을 남겨주세요. 감사합니다.
