### ISSUE TITLE
f

### ISSUE THREAD

**Issue by Joen0818** [awesome-davian/awesome-reviews-kaist#514]

**Comment by Joen0818** [comment]
안녕하세요 조교님?
전영우 입니다.

다름이 아니라, 최종 paperreview를 제출하려고 합니다.
지난번 처럼 pull request 를 눌렀으나&nbsp;
이렇게 나오고 제출이 불가해서요

혹시 제출방법이 지난번과 다른건가요?&nbsp;

감사합니다
-전영우 올림-


-----Original Message-----

**Comment by ddehun** [comment]
안녕하세요. 여기는 저희가 다른 분들의 논문 리뷰를 했던 Issue여서요, Pull requests 를 누르시면 될 것 같습니다. 감사합니다.

**Comment by Joen0818** [comment]
네 감사합니다!&nbsp;바로 제출하겠습니다!&nbsp;

감사합니다&nbsp;
-전영우 드림------Original Message-----From: ChaeHun ***@***.*** ***@***.***&gt; To: ***@***.*** ***@***.***&gt; Cc: Youngwoo, ***@***.*** ***@***.***&gt;; ***@***.*** ***@***.***&gt;Sent: 2022년 6월 12일 21시 14분 41초 GMT+9Subject: Re: [awesome-davian/awesome-reviews-kaist] f (Issue #514)&nbsp;
 
 
 
 안녕하세요. 여기는 저희가 다른 분들의 논문 리뷰를 했던 Issue여서요, Pull requests 를 누르시면 될 것 같습니다. 감사합니다.

**Comment by Joen0818** [comment]
조교님 ..ㅜㅜ 메일을 안받으셔서요!!수정할게 큰게 없어서 지난번 제출한거를 최종으로 하겠습니다!

감사합니다.
-전영우 드림-



-----Original Message-----

**Comment by Joen0818** [comment]
안녕하세요 조교님...

다시한번 시도해도 pull request가 안되어서요..&nbsp;

지난 번 이랑 조금 다른것 같은데 혹시 확인 한 번 만 부탁드리겠습니다.

감사합니다.

-전영우 올림-



-----Original Message-----
